// STAGING name proposals for the Vulcan ตรวจทาน (name-review) tab — NOT the live catalog.
// Generated from the name-normalization workflow (decapitalise ALL-CAPS, restructure to
// "Brand Model – Descriptor (size)", size last & omitted when a product has a single size,
// keep shade codes in-name, keep the "Ortho" prefix). needsReview = the AI could not resolve a
// shade/variant and it must be checked with the team (e.g. Self Cure Dentine, H.C.D).
//
// Loading these fills ONLY Product.proposedNameEn (staging). The live Product.nameEn changes
// only when a proposal is APPROVED in Vulcan → then this file is the durable record so a future
// catalog re-seed keeps the approved names. Regenerate: scratchpad/norm/gen-proposals.ts.
//
// 994 proposals | 907 rename the product | 397 flagged for team review.

export interface NameProposal {
  sku: string;
  nameEn: string;
  needsReview: boolean;
}

export const NAME_PROPOSALS: NameProposal[] = [
  {"sku":"01-01-01","nameEn":"Tray Material (1 kg)","needsReview":false},
  {"sku":"01-01-02","nameEn":"Tray Material (500 g)","needsReview":false},
  {"sku":"01-01-03","nameEn":"Tray Material (1 kg)","needsReview":false},
  {"sku":"01-01-04","nameEn":"Tray Material (500 g)","needsReview":false},
  {"sku":"01-01-05","nameEn":"Tray Material (1 kg)","needsReview":false},
  {"sku":"01-01-06","nameEn":"Tray Material (500 g)","needsReview":false},
  {"sku":"01-01-34","nameEn":"Hard Splint (0.5 mm)","needsReview":false},
  {"sku":"01-01-35","nameEn":"Hard Splint (0.625 mm)","needsReview":false},
  {"sku":"01-01-38","nameEn":"Hard Splint (1.5 mm)","needsReview":false},
  {"sku":"01-01-39","nameEn":"Hard Splint (1 mm)","needsReview":false},
  {"sku":"01-01-43","nameEn":"Hard Splint (0.63 mm)","needsReview":false},
  {"sku":"01-01-44","nameEn":"Hard Splint (0.75 mm)","needsReview":false},
  {"sku":"01-01-45","nameEn":"Hard Splint (1 mm)","needsReview":false},
  {"sku":"01-02-01","nameEn":"Self Cure #38 / #39 (1 kg)","needsReview":false},
  {"sku":"01-02-02","nameEn":"Self Cure #38 / #39 (500 g)","needsReview":false},
  {"sku":"01-02-04","nameEn":"Self Cure #38 / #39 (1 kg)","needsReview":false},
  {"sku":"01-02-05","nameEn":"Self Cure #38 / #39 (500 g)","needsReview":false},
  {"sku":"01-02-07","nameEn":"Self Cure Clear (1 kg)","needsReview":false},
  {"sku":"01-02-08","nameEn":"Self Cure Clear (500 g)","needsReview":false},
  {"sku":"01-03-01","nameEn":"Heat Cure Acrylic (1 kg)","needsReview":true},
  {"sku":"01-03-02","nameEn":"Heat Cure Acrylic (500 g)","needsReview":true},
  {"sku":"01-03-05","nameEn":"Heat Cure Clear (1 kg)","needsReview":false},
  {"sku":"01-03-06","nameEn":"Heat Cure Clear (500 g)","needsReview":false},
  {"sku":"01-03-09","nameEn":"Heat Cure Acrylic (1 kg)","needsReview":true},
  {"sku":"01-03-10","nameEn":"Heat Cure Acrylic (500 g)","needsReview":true},
  {"sku":"01-03-17","nameEn":"Heat Cure Acrylic (1 kg)","needsReview":true},
  {"sku":"01-03-18","nameEn":"Heat Cure Acrylic (500 g)","needsReview":true},
  {"sku":"01-03-21","nameEn":"Heat Cure Acrylic (1 kg)","needsReview":true},
  {"sku":"01-03-22","nameEn":"Heat Cure Acrylic (500 g)","needsReview":true},
  {"sku":"01-03-25","nameEn":"Heat Cure Acrylic (1 kg)","needsReview":true},
  {"sku":"01-03-26","nameEn":"Heat Cure Acrylic (500 g)","needsReview":true},
  {"sku":"01-04-01","nameEn":"Pattern Resin","needsReview":false},
  {"sku":"01-07-01","nameEn":"Major Base – MV (1 kg)","needsReview":false},
  {"sku":"01-07-02","nameEn":"Major Base – MV (500 g)","needsReview":false},
  {"sku":"01-07-03","nameEn":"Major Base 20 – KV (1 kg)","needsReview":false},
  {"sku":"01-07-04","nameEn":"Major Base 20 – KV (500 g)","needsReview":false},
  {"sku":"01-07-05","nameEn":"Major Base 20 – IV (1 kg)","needsReview":false},
  {"sku":"01-07-06","nameEn":"Major Base 20 – IV (500 g)","needsReview":false},
  {"sku":"01-08-01","nameEn":"Heat Cure Acrylic (Italy) – KIV (1 kg)","needsReview":false},
  {"sku":"01-08-02","nameEn":"Heat Cure Acrylic (Italy) – KIV (500 g)","needsReview":false},
  {"sku":"01-09-03","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-09-06","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-09-09","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-09-12","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-09-15","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-09-18","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-09-21","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-09-24","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-09-27","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-09-30","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-09-33","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-09-52","nameEn":"Self Cure Dentine (Germany)","needsReview":true},
  {"sku":"01-10-06","nameEn":"Self Cure Dentine (Italy)","needsReview":true},
  {"sku":"01-10-09","nameEn":"Self Cure Dentine (Italy)","needsReview":true},
  {"sku":"01-10-12","nameEn":"Self Cure Dentine (Italy)","needsReview":true},
  {"sku":"01-10-15","nameEn":"Self Cure Dentine (Italy)","needsReview":true},
  {"sku":"01-10-18","nameEn":"Self Cure Dentine (Italy)","needsReview":true},
  {"sku":"01-10-21","nameEn":"Self Cure Dentine (Italy)","needsReview":true},
  {"sku":"01-10-24","nameEn":"Self Cure Dentine (Italy)","needsReview":true},
  {"sku":"01-10-27","nameEn":"Self Cure Dentine (Italy)","needsReview":true},
  {"sku":"01-11-02","nameEn":"H.C.D (Italy) – 50 g","needsReview":true},
  {"sku":"01-11-04","nameEn":"H.C.D (Italy) – 50 g","needsReview":true},
  {"sku":"01-11-06","nameEn":"H.C.D (Italy) – 50 g","needsReview":true},
  {"sku":"01-11-08","nameEn":"H.C.D (Italy) – 50 g","needsReview":true},
  {"sku":"01-11-10","nameEn":"H.C.D (Italy) – 50 g","needsReview":true},
  {"sku":"01-11-12","nameEn":"H.C.D (Italy) – 50 g","needsReview":true},
  {"sku":"01-11-14","nameEn":"H.C.D (Italy) – 50 g","needsReview":true},
  {"sku":"01-11-16","nameEn":"H.C.D (Italy) – 50 g","needsReview":true},
  {"sku":"01-11-18","nameEn":"H.C.D (Italy) – 50 g","needsReview":true},
  {"sku":"01-11-20","nameEn":"H.C.D (Italy) – 50 g","needsReview":true},
  {"sku":"01-11-22","nameEn":"H.C.D (Italy) – 50 g","needsReview":true},
  {"sku":"01-11-23","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-24","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-25","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-26","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-27","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-28","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-29","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-30","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-31","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-32","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-33","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-34","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-11-35","nameEn":"H.C.D (Italy) – 1 kg","needsReview":true},
  {"sku":"01-12-01","nameEn":"Ortho Plast Powder – 1 kg","needsReview":false},
  {"sku":"01-12-02","nameEn":"Ortho Plast Powder – 500 g","needsReview":false},
  {"sku":"01-13-03","nameEn":"Rapid Simplified/7 – 1 kg","needsReview":false},
  {"sku":"01-13-04","nameEn":"Rapid Simplified/7 – 500 g","needsReview":false},
  {"sku":"01-13-05","nameEn":"Rapid Simplified/10 – 1 kg","needsReview":false},
  {"sku":"01-13-06","nameEn":"Rapid Simplified/10 – 500 g","needsReview":false},
  {"sku":"01-13-07","nameEn":"Vertex Regular/7 – 1 kg","needsReview":false},
  {"sku":"01-13-08","nameEn":"Vertex Regular/7 – 500 g","needsReview":false},
  {"sku":"01-13-09","nameEn":"Vertex Regular/10 – 1 kg","needsReview":false},
  {"sku":"01-13-10","nameEn":"Vertex Regular/10 – 500 g","needsReview":false},
  {"sku":"01-14-01","nameEn":"Ortho Powder PPF 001","needsReview":false},
  {"sku":"01-14-04","nameEn":"Ortho Powder PPF 002","needsReview":false},
  {"sku":"01-14-07","nameEn":"Ortho Powder PPF 003","needsReview":false},
  {"sku":"01-14-10","nameEn":"Ortho Powder PPF 004","needsReview":false},
  {"sku":"01-14-13","nameEn":"Ortho Powder PMF 005","needsReview":false},
  {"sku":"01-14-16","nameEn":"Ortho Powder PYF 006","needsReview":false},
  {"sku":"01-14-19","nameEn":"Ortho Powder PGF 007","needsReview":false},
  {"sku":"01-14-22","nameEn":"Ortho Powder PBF 008","needsReview":false},
  {"sku":"01-14-25","nameEn":"Ortho Powder PVF 009","needsReview":false},
  {"sku":"01-14-28","nameEn":"Ortho Powder PY 010","needsReview":false},
  {"sku":"01-14-34","nameEn":"Ortho Powder PG 012","needsReview":false},
  {"sku":"01-14-37","nameEn":"Ortho Powder PR 013","needsReview":false},
  {"sku":"01-14-40","nameEn":"Ortho Powder PV 014","needsReview":false},
  {"sku":"01-14-43","nameEn":"Ortho Powder PB 015","needsReview":false},
  {"sku":"01-14-46","nameEn":"Ortho Powder PPF 016","needsReview":false},
  {"sku":"01-15-01","nameEn":"Ortho Powder DPPF 001","needsReview":false},
  {"sku":"01-15-04","nameEn":"Ortho Powder DPPF 002","needsReview":false},
  {"sku":"01-15-07","nameEn":"Ortho Powder DPPF 003","needsReview":false},
  {"sku":"01-15-10","nameEn":"Ortho Powder DPRF 004","needsReview":false},
  {"sku":"01-15-13","nameEn":"Ortho Powder DPMF 005","needsReview":false},
  {"sku":"01-15-16","nameEn":"Ortho Powder DPYF 006","needsReview":false},
  {"sku":"01-15-19","nameEn":"Ortho Powder DPGF 007","needsReview":false},
  {"sku":"01-15-22","nameEn":"Ortho Powder DPBF 008","needsReview":false},
  {"sku":"01-15-25","nameEn":"Ortho Powder DPVF 009","needsReview":false},
  {"sku":"01-15-28","nameEn":"Ortho Powder DPY 010","needsReview":false},
  {"sku":"01-15-31","nameEn":"Ortho Powder DPY 011","needsReview":false},
  {"sku":"01-15-34","nameEn":"Ortho Powder DPG 012","needsReview":false},
  {"sku":"01-15-37","nameEn":"Ortho Powder DPR 013","needsReview":false},
  {"sku":"01-15-40","nameEn":"Ortho Powder DPV 014","needsReview":false},
  {"sku":"01-15-43","nameEn":"Ortho Powder DPB 015","needsReview":false},
  {"sku":"01-15-46","nameEn":"Ortho Powder DPPF 016","needsReview":false},
  {"sku":"01-15-49","nameEn":"Ortho Powder DPYW 016","needsReview":false},
  {"sku":"01-16-01","nameEn":"Ortho Powder DP White 001","needsReview":false},
  {"sku":"01-16-04","nameEn":"Ortho Powder DP Black","needsReview":false},
  {"sku":"02-01-03","nameEn":"Monomer Self Cure – Normal set (250 ml)","needsReview":false},
  {"sku":"02-01-04","nameEn":"Monomer Self Cure – Normal set (125 ml)","needsReview":false},
  {"sku":"02-02-03","nameEn":"Monomer Self Cure – 250 ml","needsReview":false},
  {"sku":"02-02-04","nameEn":"Monomer Self Cure – 125 ml","needsReview":false},
  {"sku":"02-03-03","nameEn":"Monomer Heat Cure – Clear","needsReview":false},
  {"sku":"02-04-03","nameEn":"Monomer Heat Cure","needsReview":true},
  {"sku":"02-05-03","nameEn":"Monomer Heat Cure","needsReview":true},
  {"sku":"02-07-03","nameEn":"Monomer Tray – Fast set (250 ml)","needsReview":false},
  {"sku":"02-07-04","nameEn":"Monomer Tray – Fast set (125 ml)","needsReview":false},
  {"sku":"02-15-03","nameEn":"Monomer Ortho – Clear","needsReview":false},
  {"sku":"02-15-15","nameEn":"Diamond A80 HP","needsReview":false},
  {"sku":"02-15-20","nameEn":"Diamond R5","needsReview":false},
  {"sku":"02-15-22","nameEn":"Diamond 1LR HP","needsReview":false},
  {"sku":"02-15-37","nameEn":"Diamond 10X","needsReview":false},
  {"sku":"02-29-04","nameEn":"Steel No.75 (040)","needsReview":false},
  {"sku":"02-29-05","nameEn":"Steel No.75 (050)","needsReview":false},
  {"sku":"02-29-07","nameEn":"Steel No.75 (070)","needsReview":false},
  {"sku":"02-29-08","nameEn":"Steel No.77 (070)","needsReview":false},
  {"sku":"02-29-09","nameEn":"Steel No.77 (080)","needsReview":false},
  {"sku":"02-29-45","nameEn":"Steel No.75 (045)","needsReview":false},
  {"sku":"02-29-50","nameEn":"Steel No.78 (050)","needsReview":false},
  {"sku":"02-29-55","nameEn":"Steel No.79 (055)","needsReview":false},
  {"sku":"02-42-03","nameEn":"Carbide HP1 (006F/0,6)","needsReview":false},
  {"sku":"02-42-04","nameEn":"Carbide HP2 (010F/1,0)","needsReview":false},
  {"sku":"02-42-05","nameEn":"Carbide HP3 (012F/1,2)","needsReview":false},
  {"sku":"02-42-06","nameEn":"Carbide HP6 (018F/1,8)","needsReview":false},
  {"sku":"02-42-08","nameEn":"Carbide HP700 (010F/4,0)","needsReview":false},
  {"sku":"02-42-27","nameEn":"Carbide HP701 (012F/6,0)","needsReview":false},
  {"sku":"02-42-28","nameEn":"Carbide HP702 (016F/4,0)","needsReview":false},
  {"sku":"02-42-29","nameEn":"Carbide HP703 (022F/6,0)","needsReview":false},
  {"sku":"03-04-01","nameEn":"AB309 Disk (22.2 mm × 0.25 mm)","needsReview":false},
  {"sku":"03-04-02","nameEn":"AB307 Disk (22.2 mm × 0.38 mm)","needsReview":false},
  {"sku":"03-04-03","nameEn":"Polishing Silicon Disc (22 mm × 0.2–0.25 mm)","needsReview":false},
  {"sku":"03-05-01","nameEn":"Polishing Silicon Disc (38 mm × 0.6–0.7 mm)","needsReview":false},
  {"sku":"03-05-02","nameEn":"Disk Porcelain","needsReview":false},
  {"sku":"03-05-10","nameEn":"Polishing Silicon Disc (38 mm × 1.0 mm)","needsReview":false},
  {"sku":"03-05-11","nameEn":"Polishing Silicon Disc (38 mm × 1.7 mm)","needsReview":false},
  {"sku":"03-06-12","nameEn":"AB233 Disk","needsReview":false},
  {"sku":"03-08-08","nameEn":"Trimmer Y01.040 – Modified","needsReview":false},
  {"sku":"03-08-09","nameEn":"Silicone Carbide","needsReview":true},
  {"sku":"03-08-11","nameEn":"Silicone Carbide","needsReview":true},
  {"sku":"03-16-99","nameEn":"SH354 220 (DS 0,3)","needsReview":true},
  {"sku":"03-20-03","nameEn":"Felt Polisher G9","needsReview":false},
  {"sku":"03-21-04","nameEn":"EAT Saitex #240","needsReview":false},
  {"sku":"03-22-00","nameEn":"Lamina Marker","needsReview":false},
  {"sku":"03-25-01","nameEn":"Korex (50 micron)","needsReview":false},
  {"sku":"03-25-02","nameEn":"Korex (110 micron)","needsReview":false},
  {"sku":"03-25-03","nameEn":"Korex (250 micron)","needsReview":false},
  {"sku":"03-26-01","nameEn":"Pumice","needsReview":true},
  {"sku":"03-26-02","nameEn":"Pumice","needsReview":true},
  {"sku":"03-26-03","nameEn":"Pumice","needsReview":true},
  {"sku":"03-26-07","nameEn":"Stone Type IV (box of 10)","needsReview":false},
  {"sku":"03-26-08","nameEn":"Stone Type IV (1 kg)","needsReview":false},
  {"sku":"03-30-70","nameEn":"4110 Composite Finish and Polish","needsReview":false},
  {"sku":"03-30-73","nameEn":"CP6001 Composite Polishing RA","needsReview":false},
  {"sku":"03-30-74","nameEn":"Zirconia Lithium Kit","needsReview":true},
  {"sku":"03-34-00","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-01","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-02","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-03","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-04","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-05","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-06","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-07","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-08","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-09","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-10","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-11","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-12","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-13","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-14","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-15","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-16","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-17","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-18","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-19","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-20","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-21","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-22","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-23","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-24","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-25","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-26","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-27","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-28","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-29","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-30","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-31","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-32","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-33","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-34","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-35","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-36","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-37","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-38","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-39","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-40","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-41","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-42","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-43","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-44","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-45","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-46","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-47","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-48","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-49","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-50","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-51","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-52","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-53","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-54","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-55","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-56","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-57","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-58","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-59","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-60","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-61","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-62","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-63","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-64","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-65","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-66","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-67","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-68","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-69","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-70","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-71","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-72","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-73","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-74","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-75","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-76","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-77","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-78","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-79","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-80","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-81","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-82","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-83","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-84","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-85","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-86","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-87","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-88","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-89","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-90","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-34-91","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-36-79","nameEn":"Tungsten Carbide Bur C1 (CM278)","needsReview":false},
  {"sku":"03-36-80","nameEn":"Tungsten Carbide Bur C1 (CM279)","needsReview":false},
  {"sku":"03-36-81","nameEn":"Tungsten Carbide Bur C1 (CM280)","needsReview":false},
  {"sku":"03-36-82","nameEn":"Tungsten Carbide Bur C1 (CM281)","needsReview":false},
  {"sku":"03-36-83","nameEn":"Tungsten Carbide Bur C1 (CM282)","needsReview":false},
  {"sku":"03-36-84","nameEn":"Tungsten Carbide Bur C1 (CM283)","needsReview":false},
  {"sku":"03-36-85","nameEn":"Tungsten Carbide Bur C1 (CM284)","needsReview":false},
  {"sku":"03-36-86","nameEn":"Tungsten Carbide Bur C1 (CM285)","needsReview":false},
  {"sku":"03-36-87","nameEn":"Tungsten Carbide Bur C1 (CM286)","needsReview":false},
  {"sku":"03-36-88","nameEn":"Tungsten Carbide Bur C1 (CM287)","needsReview":false},
  {"sku":"03-36-89","nameEn":"Tungsten Carbide Bur C1 (CM288)","needsReview":false},
  {"sku":"03-36-90","nameEn":"Tungsten Carbide Bur C1 (CM289)","needsReview":false},
  {"sku":"03-36-91","nameEn":"Tungsten Carbide Bur C1 (CM290)","needsReview":false},
  {"sku":"03-36-92","nameEn":"Tungsten Carbide Bur C1 (CM291)","needsReview":false},
  {"sku":"03-36-93","nameEn":"Tungsten Carbide Bur C2 (CM292)","needsReview":false},
  {"sku":"03-36-94","nameEn":"Tungsten Carbide Bur C2 (CM293)","needsReview":false},
  {"sku":"03-36-95","nameEn":"Tungsten Carbide Bur C2 (CM294)","needsReview":false},
  {"sku":"03-36-96","nameEn":"Tungsten Carbide Bur C2 (CM295)","needsReview":false},
  {"sku":"03-36-97","nameEn":"Tungsten Carbide Bur C2 (CM296)","needsReview":false},
  {"sku":"03-36-98","nameEn":"Tungsten Carbide Bur C2 (CM297)","needsReview":false},
  {"sku":"03-36-99","nameEn":"Tungsten Carbide Bur C2 (CM298)","needsReview":false},
  {"sku":"03-37-00","nameEn":"Tungsten Carbide Bur C2 (CM299)","needsReview":false},
  {"sku":"03-37-01","nameEn":"Tungsten Carbide Bur C21 (CM300)","needsReview":false},
  {"sku":"03-37-02","nameEn":"Tungsten Carbide Bur C21 (CM301)","needsReview":false},
  {"sku":"03-37-03","nameEn":"Tungsten Carbide Bur C21 (CM302)","needsReview":false},
  {"sku":"03-37-04","nameEn":"Tungsten Carbide Bur C21 (CM303)","needsReview":false},
  {"sku":"03-37-05","nameEn":"Tungsten Carbide Bur C21 (CM304)","needsReview":false},
  {"sku":"03-37-06","nameEn":"Tungsten Carbide Bur C21 (CM305)","needsReview":false},
  {"sku":"03-37-07","nameEn":"Tungsten Carbide Bur C21R (CM307)","needsReview":false},
  {"sku":"03-37-08","nameEn":"Tungsten Carbide Bur C21R (CM306)","needsReview":false},
  {"sku":"03-37-09","nameEn":"Tungsten Carbide Bur C23 (CM308)","needsReview":false},
  {"sku":"03-37-10","nameEn":"Tungsten Carbide Bur C23 (CM309)","needsReview":false},
  {"sku":"03-37-11","nameEn":"Tungsten Carbide Bur C23 (CM310)","needsReview":false},
  {"sku":"03-37-12","nameEn":"Tungsten Carbide Bur C23 (CM311) – 0.3 mm","needsReview":true},
  {"sku":"03-37-13","nameEn":"Tungsten Carbide Bur C23R (CM312)","needsReview":false},
  {"sku":"03-37-14","nameEn":"Tungsten Carbide Bur C23R (CM313)","needsReview":false},
  {"sku":"03-37-15","nameEn":"Tungsten Carbide Bur C23RS (CM314)","needsReview":false},
  {"sku":"03-37-16","nameEn":"Tungsten Carbide Bur C31 (CM315)","needsReview":false},
  {"sku":"03-37-17","nameEn":"Tungsten Carbide Bur C31 (CM316)","needsReview":false},
  {"sku":"03-37-18","nameEn":"Tungsten Carbide Bur C31 (CM317)","needsReview":false},
  {"sku":"03-37-19","nameEn":"Tungsten Carbide Bur C31 (CM318)","needsReview":false},
  {"sku":"03-37-20","nameEn":"Tungsten Carbide Bur C31 (CM319)","needsReview":false},
  {"sku":"03-37-21","nameEn":"Tungsten Carbide Bur C33 (CM320)","needsReview":false},
  {"sku":"03-37-22","nameEn":"Tungsten Carbide Bur C33 (CM321)","needsReview":false},
  {"sku":"03-37-23","nameEn":"Tungsten Carbide Bur C33 (CM322)","needsReview":false},
  {"sku":"03-37-24","nameEn":"Tungsten Carbide Bur C33 (CM323)","needsReview":false},
  {"sku":"03-37-25","nameEn":"Tungsten Carbide Bur C33 (CM324)","needsReview":false},
  {"sku":"03-37-26","nameEn":"Tungsten Carbide Bur C33L (CM325)","needsReview":false},
  {"sku":"03-37-29","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-37-30","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-37-31","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-37-32","nameEn":"Sunshine Diamonds","needsReview":true},
  {"sku":"03-47-48","nameEn":"Sr 106 M – Medium (RA)","needsReview":false},
  {"sku":"03-47-52","nameEn":"Sr 103 F – Fine (RA)","needsReview":false},
  {"sku":"03-47-54","nameEn":"Sr 106 F – Fine (RA)","needsReview":false},
  {"sku":"03-47-64","nameEn":"Sr 103 UF – Ultra fine (RA)","needsReview":false},
  {"sku":"03-47-66","nameEn":"Sr 106 UF – Ultra fine (RA)","needsReview":false},
  {"sku":"03-47-71","nameEn":"DCR 122 – Extra fine (RA)","needsReview":false},
  {"sku":"03-47-72","nameEn":"DCR 104 – Extra fine (RA)","needsReview":false},
  {"sku":"03-47-76","nameEn":"SR204C","needsReview":true},
  {"sku":"03-47-77","nameEn":"SR204M","needsReview":true},
  {"sku":"03-47-78","nameEn":"SR204F","needsReview":true},
  {"sku":"03-47-79","nameEn":"Stone Rw01","needsReview":false},
  {"sku":"03-47-80","nameEn":"Stone Rw02","needsReview":false},
  {"sku":"03-47-81","nameEn":"Stone Rw03","needsReview":false},
  {"sku":"03-47-82","nameEn":"Stone Rw04","needsReview":false},
  {"sku":"03-47-83","nameEn":"Stone Rw06","needsReview":false},
  {"sku":"03-47-84","nameEn":"Stone Fw01","needsReview":false},
  {"sku":"03-47-85","nameEn":"Stone Fw02","needsReview":false},
  {"sku":"03-47-86","nameEn":"Stone Fw03","needsReview":false},
  {"sku":"03-47-87","nameEn":"Stone Fw06","needsReview":false},
  {"sku":"03-47-88","nameEn":"Stone Rg01","needsReview":false},
  {"sku":"03-47-89","nameEn":"Stone Rg02","needsReview":false},
  {"sku":"03-47-90","nameEn":"Stone Rg06","needsReview":false},
  {"sku":"03-47-91","nameEn":"Stones FG01","needsReview":false},
  {"sku":"03-47-92","nameEn":"Stones FG02","needsReview":false},
  {"sku":"03-47-93","nameEn":"Stones FG06","needsReview":false},
  {"sku":"03-47-94","nameEn":"R4DW08","needsReview":true},
  {"sku":"03-47-95","nameEn":"R4CW03","needsReview":true},
  {"sku":"03-47-96","nameEn":"R4CC07","needsReview":true},
  {"sku":"03-47-97","nameEn":"R4CB05","needsReview":true},
  {"sku":"03-47-98","nameEn":"R4CR04","needsReview":true},
  {"sku":"03-47-99","nameEn":"R4CP02","needsReview":true},
  {"sku":"03-48-00","nameEn":"R4CY06","needsReview":true},
  {"sku":"03-48-01","nameEn":"R4G01","needsReview":true},
  {"sku":"03-48-02","nameEn":"R5DW08","needsReview":true},
  {"sku":"03-48-03","nameEn":"R5CW03","needsReview":true},
  {"sku":"03-48-04","nameEn":"R5CC07","needsReview":true},
  {"sku":"03-48-05","nameEn":"R5CB05","needsReview":true},
  {"sku":"03-48-06","nameEn":"R5CR04","needsReview":true},
  {"sku":"03-48-07","nameEn":"R5CP02","needsReview":true},
  {"sku":"03-48-08","nameEn":"R5CY","needsReview":true},
  {"sku":"03-48-13","nameEn":"R1NS","needsReview":true},
  {"sku":"03-48-22","nameEn":"R4SIC","needsReview":true},
  {"sku":"03-48-24","nameEn":"R7SIC","needsReview":true},
  {"sku":"03-48-31","nameEn":"Mandrel POP ON","needsReview":true},
  {"sku":"03-48-38","nameEn":"Mandrel 32HS","needsReview":true},
  {"sku":"04-00-01","nameEn":"Pink Wax – Thin (1 mm)","needsReview":false},
  {"sku":"04-00-02","nameEn":"Pink Wax – #1 (1.5 mm)","needsReview":false},
  {"sku":"04-00-04","nameEn":"Pink Wax – Thick (2 mm)","needsReview":false},
  {"sku":"04-01-00","nameEn":"Aluwax – Thin (0.05 mm)","needsReview":false},
  {"sku":"04-01-02","nameEn":"Aluwax – Thick (1.00 mm)","needsReview":false},
  {"sku":"04-01-09","nameEn":"Utility Wax","needsReview":true},
  {"sku":"04-01-10","nameEn":"Utility Wax","needsReview":true},
  {"sku":"04-01-11","nameEn":"Utility Wax","needsReview":true},
  {"sku":"04-02-00","nameEn":"Pink Wax S#5 – Thin","needsReview":false},
  {"sku":"04-04-00","nameEn":"Wax","needsReview":true},
  {"sku":"04-10-10","nameEn":"Occlusal Plate","needsReview":false},
  {"sku":"04-10-11","nameEn":"Occlusal Plate – Color","needsReview":false},
  {"sku":"04-12-01","nameEn":"Sticky Wax (100 pcs)","needsReview":false},
  {"sku":"04-12-03","nameEn":"Sticky Wax (12 pcs)","needsReview":false},
  {"sku":"04-13-00","nameEn":"Horseshoe Wax – #1 straight","needsReview":false},
  {"sku":"04-13-01","nameEn":"Horseshoe Wax – #2 projecting","needsReview":false},
  {"sku":"05-12-00","nameEn":"Bellavest SH (80 sachets)","needsReview":false},
  {"sku":"05-12-02","nameEn":"Bellavest SH (160 g)","needsReview":false},
  {"sku":"05-14-00","nameEn":"Liquid (1 L)","needsReview":false},
  {"sku":"05-14-02","nameEn":"Liquid (5 L)","needsReview":false},
  {"sku":"05-20-05","nameEn":"Twin Pins – Red","needsReview":false},
  {"sku":"05-20-06","nameEn":"Set of Nail with Groove A","needsReview":false},
  {"sku":"05-20-07","nameEn":"Set of Nail with Groove B","needsReview":false},
  {"sku":"05-20-09","nameEn":"Special Nails","needsReview":false},
  {"sku":"05-20-11","nameEn":"Twin Pins Nails – Medium","needsReview":false},
  {"sku":"05-29-03","nameEn":"Dental Saw","needsReview":false},
  {"sku":"06-00-00","nameEn":"Wirovest (400 g)","needsReview":false},
  {"sku":"06-00-01","nameEn":"Wirovest (45 bags)","needsReview":false},
  {"sku":"07-00-01","nameEn":"Ormaplus Putty NEO – Fast setting","needsReview":false},
  {"sku":"07-00-02","nameEn":"Ormaplus Putty NEO – Regular setting","needsReview":false},
  {"sku":"07-00-03","nameEn":"Ormaplus LV NEO – Fast setting","needsReview":false},
  {"sku":"07-00-04","nameEn":"Ormaplus LV NEO – Regular setting","needsReview":false},
  {"sku":"07-00-05","nameEn":"Ormaplus NEO Monophase","needsReview":false},
  {"sku":"07-00-06","nameEn":"Ormaplus NEO Bite","needsReview":false},
  {"sku":"07-00-07","nameEn":"Ormaplus NEO Gum Soft","needsReview":false},
  {"sku":"07-00-08","nameEn":"Ormaplus NEO Gum Hard","needsReview":false},
  {"sku":"07-01-03","nameEn":"Gelmax","needsReview":false},
  {"sku":"07-01-04","nameEn":"Alginmax New","needsReview":false},
  {"sku":"07-01-05","nameEn":"Glass Slab (Size L)","needsReview":false},
  {"sku":"07-01-07","nameEn":"Cromax","needsReview":false},
  {"sku":"07-01-08","nameEn":"Glass Slab (Size S)","needsReview":false},
  {"sku":"07-01-09","nameEn":"Glass Instrument Dish (15×100 mm)","needsReview":false},
  {"sku":"07-01-10","nameEn":"Glass Instrument Dish (25×100 mm)","needsReview":false},
  {"sku":"07-02-00","nameEn":"Ormactivator Catalyst Gel","needsReview":false},
  {"sku":"07-02-01","nameEn":"Ormadent Putty","needsReview":false},
  {"sku":"07-02-02","nameEn":"Ormamax Light","needsReview":false},
  {"sku":"07-02-12","nameEn":"Wedge","needsReview":true},
  {"sku":"07-02-13","nameEn":"Wedge","needsReview":true},
  {"sku":"07-02-14","nameEn":"Wedge","needsReview":true},
  {"sku":"07-02-16","nameEn":"Novosyn","needsReview":true},
  {"sku":"07-02-17","nameEn":"Novosyn","needsReview":true},
  {"sku":"07-02-19","nameEn":"Diamond Wedges – Small","needsReview":false},
  {"sku":"07-02-20","nameEn":"Diamond Wedges – Medium","needsReview":false},
  {"sku":"07-02-24","nameEn":"Ormaplus LV – Normal setting","needsReview":false},
  {"sku":"07-02-32","nameEn":"Mouth Retractor","needsReview":true},
  {"sku":"07-02-33","nameEn":"Mouth Retractor","needsReview":true},
  {"sku":"07-02-36","nameEn":"Cheek Retractor – With handles, soft","needsReview":true},
  {"sku":"07-02-37","nameEn":"Cheek Retractor – With handles, soft","needsReview":true},
  {"sku":"07-03-07","nameEn":"Silicone Mixing Cup (M)","needsReview":false},
  {"sku":"07-03-08","nameEn":"Silicone Mixing Cup (L)","needsReview":false},
  {"sku":"07-03-18","nameEn":"Dappen Dish","needsReview":false},
  {"sku":"07-03-20","nameEn":"Surgical Drape (15×18 in)","needsReview":true},
  {"sku":"07-03-21","nameEn":"Surgical Drape (15×18 in)","needsReview":true},
  {"sku":"07-03-22","nameEn":"Surgical Drape (15×18 in)","needsReview":true},
  {"sku":"07-03-23","nameEn":"Surgical Drape (30×36 in)","needsReview":true},
  {"sku":"07-03-24","nameEn":"Surgical Drape (30×36 in)","needsReview":true},
  {"sku":"07-03-25","nameEn":"Surgical Drape (30×36 in)","needsReview":true},
  {"sku":"07-03-26","nameEn":"Surgical Wrapping Drape (18×18 in)","needsReview":true},
  {"sku":"07-03-27","nameEn":"Surgical Wrapping Drape (18×18 in)","needsReview":true},
  {"sku":"07-03-28","nameEn":"Surgical Wrapping Drape (18×18 in)","needsReview":true},
  {"sku":"07-03-29","nameEn":"Surgical Wrapping Drape (22×24 in)","needsReview":true},
  {"sku":"07-03-30","nameEn":"Surgical Wrapping Drape (22×24 in)","needsReview":true},
  {"sku":"07-03-31","nameEn":"Surgical Wrapping Drape (22×24 in)","needsReview":true},
  {"sku":"07-03-51","nameEn":"Flexible Mixing Bowl (M)","needsReview":false},
  {"sku":"07-03-52","nameEn":"Flexible Mixing Bowl (L)","needsReview":false},
  {"sku":"07-03-61","nameEn":"Flexible Mixing Bowl (M)","needsReview":true},
  {"sku":"07-03-62","nameEn":"Flexible Mixing Bowl (L)","needsReview":true},
  {"sku":"07-04-02","nameEn":"Pure Gloves","needsReview":true},
  {"sku":"07-04-03","nameEn":"Pure Gloves","needsReview":true},
  {"sku":"07-04-04","nameEn":"Pure Gloves","needsReview":true},
  {"sku":"07-04-05","nameEn":"Pure Gloves","needsReview":true},
  {"sku":"07-04-10","nameEn":"Surgical Drape (15×18 in)","needsReview":false},
  {"sku":"07-04-11","nameEn":"Surgical Drape (30×36 in)","needsReview":false},
  {"sku":"07-04-20","nameEn":"Surgical Wrapping Drape (18×18 in)","needsReview":false},
  {"sku":"07-04-21","nameEn":"Surgical Wrapping Drape (22×24 in)","needsReview":false},
  {"sku":"07-04-26","nameEn":"Disposable Bed Sheet","needsReview":false},
  {"sku":"07-05-10","nameEn":"Fluoride Gel PRO-F","needsReview":true},
  {"sku":"07-05-11","nameEn":"Fluoride Gel PRO-F","needsReview":true},
  {"sku":"07-05-13","nameEn":"Fluoride Gel PRO-F","needsReview":true},
  {"sku":"07-05-30","nameEn":"Membrane (15×30×0.3 mm)","needsReview":true},
  {"sku":"07-05-33","nameEn":"Biocera-F (1.0–2.0 mm / 0.50 cc)","needsReview":false},
  {"sku":"07-05-34","nameEn":"Biocera-F (1.0–2.0 mm / 0.25 cc)","needsReview":false},
  {"sku":"07-06-16","nameEn":"Gauze 24×20 ตัด 6","needsReview":true},
  {"sku":"07-06-30","nameEn":"Syringe (3 ml)","needsReview":true},
  {"sku":"07-06-31","nameEn":"Syringe (5 ml)","needsReview":true},
  {"sku":"07-06-32","nameEn":"Syringe (10 ml)","needsReview":true},
  {"sku":"07-06-33","nameEn":"Syringe (20 ml)","needsReview":true},
  {"sku":"07-06-35","nameEn":"Syringe (20 ml)","needsReview":true},
  {"sku":"07-06-36","nameEn":"Syringe (10 ml)","needsReview":true},
  {"sku":"07-06-37","nameEn":"Syringe (5 ml)","needsReview":true},
  {"sku":"07-06-38","nameEn":"Syringe (3 ml)","needsReview":true},
  {"sku":"07-07-01","nameEn":"Dental Needle – G-30 short","needsReview":false},
  {"sku":"07-07-02","nameEn":"Dental Needle – G-27","needsReview":true},
  {"sku":"07-07-03","nameEn":"Dental Needle – G-27","needsReview":true},
  {"sku":"07-07-04","nameEn":"Non Woven Cap","needsReview":true},
  {"sku":"07-07-05","nameEn":"Non Woven Cap","needsReview":true},
  {"sku":"07-07-17","nameEn":"Cotton Plier","needsReview":false},
  {"sku":"07-07-18","nameEn":"Mosquito Forcep – Straight large short tip","needsReview":false},
  {"sku":"07-07-20","nameEn":"Blade Paramount","needsReview":true},
  {"sku":"07-07-21","nameEn":"Blade Paramount","needsReview":true},
  {"sku":"07-07-30","nameEn":"Non Woven Cap","needsReview":true},
  {"sku":"07-07-31","nameEn":"Non Woven Cap","needsReview":true},
  {"sku":"07-07-32","nameEn":"Non Woven Cap","needsReview":true},
  {"sku":"07-07-33","nameEn":"Non Woven Cap","needsReview":true},
  {"sku":"07-07-50","nameEn":"Fish Mask","needsReview":true},
  {"sku":"07-07-51","nameEn":"Fish Mask","needsReview":true},
  {"sku":"07-07-61","nameEn":"Surgical Mask","needsReview":true},
  {"sku":"07-07-62","nameEn":"Surgical Mask","needsReview":true},
  {"sku":"07-07-63","nameEn":"Surgical Mask","needsReview":true},
  {"sku":"07-07-64","nameEn":"Surgical Mask","needsReview":true},
  {"sku":"07-07-65","nameEn":"Surgical Mask","needsReview":true},
  {"sku":"07-07-66","nameEn":"Surgical Mask","needsReview":true},
  {"sku":"07-07-67","nameEn":"Surgical Mask","needsReview":true},
  {"sku":"07-07-71","nameEn":"Surgical Mask Kids","needsReview":true},
  {"sku":"07-07-72","nameEn":"Surgical Mask Kids","needsReview":true},
  {"sku":"07-07-73","nameEn":"Surgical Mask Kids","needsReview":true},
  {"sku":"07-07-74","nameEn":"Surgical Mask Kids","needsReview":true},
  {"sku":"07-07-75","nameEn":"Surgical Mask Kids","needsReview":true},
  {"sku":"07-07-76","nameEn":"Surgical Mask Kids","needsReview":true},
  {"sku":"07-07-77","nameEn":"Surgical Mask Kids","needsReview":true},
  {"sku":"07-08-00","nameEn":"Feather Blade","needsReview":true},
  {"sku":"07-08-01","nameEn":"Feather Blade","needsReview":true},
  {"sku":"07-08-02","nameEn":"Feather Blade","needsReview":true},
  {"sku":"07-08-03","nameEn":"Scalpel Handle","needsReview":false},
  {"sku":"07-08-04","nameEn":"P10 Scaler","needsReview":true},
  {"sku":"07-08-05","nameEn":"Ivory Light Weight Rubber Dam Clamp","needsReview":true},
  {"sku":"07-08-06","nameEn":"Brewer Rubber Dam Clamp","needsReview":false},
  {"sku":"07-08-07","nameEn":"Feather Blade","needsReview":true},
  {"sku":"07-08-08","nameEn":"Mouth Mirror","needsReview":false},
  {"sku":"07-08-09","nameEn":"Mouth Mirror","needsReview":true},
  {"sku":"07-08-10","nameEn":"Aspirating Syringe","needsReview":false},
  {"sku":"07-08-12","nameEn":"Amalgam Carrier","needsReview":false},
  {"sku":"07-08-13","nameEn":"Amalgam Well","needsReview":false},
  {"sku":"07-08-14","nameEn":"Mathieu Needle Holder","needsReview":false},
  {"sku":"07-08-15","nameEn":"Mathieu Needle Holder with Hook","needsReview":false},
  {"sku":"07-08-17","nameEn":"Mathieu Needle Holder (Gold handle)","needsReview":false},
  {"sku":"07-08-19","nameEn":"Mosquito Forcep – Straight small tip","needsReview":false},
  {"sku":"07-08-20","nameEn":"Mosquito Forcep – Curved tip","needsReview":false},
  {"sku":"07-08-21","nameEn":"Needle Holder (Gold handle)","needsReview":false},
  {"sku":"07-08-23","nameEn":"Needle Holder (Big)","needsReview":false},
  {"sku":"07-08-24","nameEn":"Plaster Nippers","needsReview":false},
  {"sku":"07-08-25","nameEn":"Spatula (Straight tip)","needsReview":false},
  {"sku":"07-08-26","nameEn":"Spatula (Curved tip)","needsReview":false},
  {"sku":"07-08-27","nameEn":"Spatula (Blade tip)","needsReview":false},
  {"sku":"07-08-28","nameEn":"Plaster Knife","needsReview":false},
  {"sku":"07-08-30","nameEn":"Spatula (Plastic)","needsReview":false},
  {"sku":"07-08-33","nameEn":"Bridge Remover","needsReview":false},
  {"sku":"07-08-37","nameEn":"Extraction Forceps – Upper primary Fig. 150S","needsReview":false},
  {"sku":"07-08-38","nameEn":"Extraction Forceps – Lower primary Fig. 151S","needsReview":false},
  {"sku":"07-08-39","nameEn":"Extraction Forceps – Upper Fig. 150","needsReview":false},
  {"sku":"07-08-40","nameEn":"Extraction Forceps – Lower Fig. 151","needsReview":false},
  {"sku":"07-08-42","nameEn":"Extraction Forceps (Cow Horn)","needsReview":false},
  {"sku":"07-08-43","nameEn":"Triple Syringe","needsReview":false},
  {"sku":"07-08-45","nameEn":"Molt Periosteal Elevator","needsReview":false},
  {"sku":"07-08-46","nameEn":"Adson Tissue Forceps (12 cm)","needsReview":false},
  {"sku":"07-08-48","nameEn":"Gum Scissors (Curved tip)","needsReview":false},
  {"sku":"07-08-49","nameEn":"Wax Knife","needsReview":true},
  {"sku":"07-08-50","nameEn":"Wax Knife","needsReview":true},
  {"sku":"07-08-51","nameEn":"Lucas CL86 Bone Curette (Medium)","needsReview":false},
  {"sku":"07-08-52","nameEn":"Lucas CL86 Bone Curette (Big)","needsReview":false},
  {"sku":"07-08-53","nameEn":"Roach Carver (Small blade tip)","needsReview":false},
  {"sku":"07-08-54","nameEn":"Roach Carver (Spear tip)","needsReview":false},
  {"sku":"07-08-55","nameEn":"Spoon Excavator (Small)","needsReview":false},
  {"sku":"07-08-56","nameEn":"Finger Mini Cup","needsReview":false},
  {"sku":"07-08-57","nameEn":"Cement Spatula","needsReview":false},
  {"sku":"07-08-60","nameEn":"Amalgam Carver","needsReview":false},
  {"sku":"07-08-62","nameEn":"Dycal Carrier","needsReview":false},
  {"sku":"07-08-64","nameEn":"Angle Plier #2710","needsReview":false},
  {"sku":"07-08-65","nameEn":"Light Wire Bending Plier","needsReview":true},
  {"sku":"07-08-66","nameEn":"Johnson Plier","needsReview":true},
  {"sku":"07-08-70","nameEn":"Bracket Remover – Posterior","needsReview":false},
  {"sku":"07-08-71","nameEn":"Bracket Remover – Anterior","needsReview":false},
  {"sku":"07-08-72","nameEn":"Wire Cutting Plier – Gold handle","needsReview":false},
  {"sku":"07-08-73","nameEn":"Clasp Bending Plier","needsReview":false},
  {"sku":"07-08-74","nameEn":"De La Rosa Plier","needsReview":false},
  {"sku":"07-08-75","nameEn":"Spreader","needsReview":false},
  {"sku":"07-08-76","nameEn":"Spoon Excavator 1704S","needsReview":false},
  {"sku":"07-08-77","nameEn":"Spoon Excavator Teardrop 1764M","needsReview":false},
  {"sku":"07-08-78","nameEn":"Tweed Angle Arch Bending Plier","needsReview":false},
  {"sku":"07-08-79","nameEn":"Wire Bending Plier","needsReview":false},
  {"sku":"07-08-80","nameEn":"Nance Plier","needsReview":false},
  {"sku":"07-08-81","nameEn":"Bracket Tweezers","needsReview":false},
  {"sku":"07-08-82","nameEn":"Hollenback Plugger No.02","needsReview":false},
  {"sku":"07-08-83","nameEn":"Hollenback Wax Carver Fig.3","needsReview":false},
  {"sku":"07-08-85","nameEn":"Spoon Excavator Teardrop 1709L","needsReview":false},
  {"sku":"07-08-88","nameEn":"Aderer Plier – Medium","needsReview":false},
  {"sku":"07-08-89","nameEn":"Aderer Plier – Large","needsReview":false},
  {"sku":"07-08-91","nameEn":"Wire Bending Plier – Round/large round","needsReview":false},
  {"sku":"07-08-93","nameEn":"Wire Bending Plier – Round/small","needsReview":false},
  {"sku":"07-08-94","nameEn":"Wire Bending Plier – Round/flat","needsReview":false},
  {"sku":"07-08-95","nameEn":"Wire Bending Plier – Flat/white","needsReview":false},
  {"sku":"07-08-96","nameEn":"Wire Bending Plier – Flat/short flat","needsReview":false},
  {"sku":"07-08-97","nameEn":"Loop Forming Plier","needsReview":false},
  {"sku":"07-08-98","nameEn":"Round and Concave Plier","needsReview":false},
  {"sku":"07-09-01","nameEn":"Spatula Spoon","needsReview":false},
  {"sku":"07-09-02","nameEn":"Spatula – Blade tip","needsReview":false},
  {"sku":"07-09-03","nameEn":"Spatula – Blade tip, large","needsReview":false},
  {"sku":"07-09-04","nameEn":"Spatula #7","needsReview":false},
  {"sku":"07-09-05","nameEn":"Spatula – Edge","needsReview":false},
  {"sku":"07-09-06","nameEn":"Hylin Carver","needsReview":false},
  {"sku":"07-09-07","nameEn":"Lecron Carver","needsReview":false},
  {"sku":"07-09-08","nameEn":"Zahle Carver","needsReview":true},
  {"sku":"07-09-10","nameEn":"Gridman Spatula","needsReview":true},
  {"sku":"07-09-11","nameEn":"Wax Caliper","needsReview":false},
  {"sku":"07-09-12","nameEn":"Metal Caliper","needsReview":false},
  {"sku":"07-09-18","nameEn":"Root Elevator (Cryer) – Left","needsReview":false},
  {"sku":"07-09-19","nameEn":"Root Elevator (Cryer) – Right","needsReview":false},
  {"sku":"07-09-20","nameEn":"Operating Scissors","needsReview":false},
  {"sku":"07-09-22","nameEn":"Band Pusher","needsReview":false},
  {"sku":"07-09-23","nameEn":"Adams Clasp Plier","needsReview":false},
  {"sku":"07-09-27","nameEn":"Rubber Dam Punch","needsReview":false},
  {"sku":"07-09-28","nameEn":"Interproximal Carver","needsReview":false},
  {"sku":"07-09-29","nameEn":"Periosteal Elevator","needsReview":false},
  {"sku":"07-09-30","nameEn":"Cheek Retractor","needsReview":false},
  {"sku":"07-09-31","nameEn":"Root Tip Pick","needsReview":false},
  {"sku":"07-09-33","nameEn":"Scaler H6-7 – Curved","needsReview":false},
  {"sku":"07-09-34","nameEn":"Gracey Curette","needsReview":true},
  {"sku":"07-09-35","nameEn":"Periodontal Probe – 10 markings","needsReview":false},
  {"sku":"07-09-36","nameEn":"Root Elevator (Flieht) – Left","needsReview":true},
  {"sku":"07-09-37","nameEn":"Root Elevator (Flieht) – Right","needsReview":true},
  {"sku":"07-09-38","nameEn":"Root Tip Elevator – Left","needsReview":false},
  {"sku":"07-09-39","nameEn":"Root Tip Elevator – Right","needsReview":false},
  {"sku":"07-09-44","nameEn":"Root Elevator – Large tip","needsReview":false},
  {"sku":"07-09-45","nameEn":"Root Elevator – Small tip","needsReview":false},
  {"sku":"07-09-46","nameEn":"Root Luxator – Straight","needsReview":false},
  {"sku":"07-09-47","nameEn":"Root Luxator – Curved","needsReview":false},
  {"sku":"07-09-48","nameEn":"Root Elevator 4.00 – Straight","needsReview":false},
  {"sku":"07-09-49","nameEn":"Root Luxator","needsReview":true},
  {"sku":"07-09-50","nameEn":"Root Luxator","needsReview":true},
  {"sku":"07-09-51","nameEn":"Root Elevator 3.00 – Curved","needsReview":false},
  {"sku":"07-09-61","nameEn":"MQ-Y005","needsReview":true},
  {"sku":"07-09-62","nameEn":"MQ-Y022","needsReview":true},
  {"sku":"07-09-63","nameEn":"MQ-Y001A","needsReview":true},
  {"sku":"07-09-64","nameEn":"MQ-Y00012","needsReview":true},
  {"sku":"07-09-65","nameEn":"MQ-Y014A","needsReview":true},
  {"sku":"07-09-74","nameEn":"Periodontal Probe – 15 markings","needsReview":false},
  {"sku":"07-10-02","nameEn":"Suction Tip – Large","needsReview":false},
  {"sku":"07-10-03","nameEn":"Suction Tip","needsReview":false},
  {"sku":"07-10-09","nameEn":"Suction Tip – Clear (100 pcs)","needsReview":false},
  {"sku":"07-10-11","nameEn":"Suction Tip – Mixed color (100 pcs)","needsReview":false},
  {"sku":"07-10-20","nameEn":"Suction Tip","needsReview":true},
  {"sku":"07-10-21","nameEn":"Suction Tip","needsReview":true},
  {"sku":"07-10-22","nameEn":"Suction Tip","needsReview":true},
  {"sku":"07-11-00","nameEn":"Major Dent","needsReview":true},
  {"sku":"07-11-02","nameEn":"Impression Trays","needsReview":true},
  {"sku":"07-11-03","nameEn":"Mouth Mirror (10 pcs set)","needsReview":false},
  {"sku":"07-11-04","nameEn":"Haemostatic Sponge","needsReview":false},
  {"sku":"07-11-06","nameEn":"Microbrush","needsReview":true},
  {"sku":"07-11-07","nameEn":"Microbrush","needsReview":true},
  {"sku":"07-11-08","nameEn":"Microbrush","needsReview":true},
  {"sku":"07-11-10","nameEn":"Long Microbrush (8 mm)","needsReview":false},
  {"sku":"07-11-11","nameEn":"Long Microbrush (8 mm)","needsReview":false},
  {"sku":"07-11-20","nameEn":"Brass Dowel Pin (1.95 mm)","needsReview":false},
  {"sku":"07-11-21","nameEn":"Brass Dowel Pin (2 mm)","needsReview":false},
  {"sku":"07-11-24","nameEn":"Surgical Blades","needsReview":true},
  {"sku":"07-11-25","nameEn":"Bite Registration Tray (25 pcs)","needsReview":false},
  {"sku":"07-11-26","nameEn":"Surgical Blades","needsReview":true},
  {"sku":"07-11-27","nameEn":"Surgical Blades","needsReview":true},
  {"sku":"07-11-28","nameEn":"Surgical Blades","needsReview":true},
  {"sku":"07-11-29","nameEn":"Fluoride Foam Tray","needsReview":true},
  {"sku":"07-11-30","nameEn":"Fluoride Foam Tray","needsReview":true},
  {"sku":"07-11-31","nameEn":"Fluoride Foam Tray","needsReview":true},
  {"sku":"07-11-32","nameEn":"Mouth Prop","needsReview":true},
  {"sku":"07-11-33","nameEn":"Mouth Prop","needsReview":true},
  {"sku":"07-11-34","nameEn":"Mouth Prop","needsReview":true},
  {"sku":"07-11-35","nameEn":"Face Shield","needsReview":false},
  {"sku":"07-11-37","nameEn":"Cheek Retractor","needsReview":false},
  {"sku":"07-11-39","nameEn":"Impression Dispenser Gun – 1:1 / 2:1","needsReview":false},
  {"sku":"07-11-40","nameEn":"Impression Dispenser Gun – 4:1 / 10:1","needsReview":false},
  {"sku":"07-11-41","nameEn":"Protective Film (1200 pcs/roll)","needsReview":false},
  {"sku":"07-11-47","nameEn":"Sandblasting Machine","needsReview":false},
  {"sku":"07-11-48","nameEn":"Alginate Mixing Machine","needsReview":false},
  {"sku":"07-11-53","nameEn":"Cleaning Powder (500 g)","needsReview":false},
  {"sku":"07-11-54","nameEn":"Articulating Paper Red – Full mouth (40 sheets/book, 6 books/box)","needsReview":false},
  {"sku":"07-11-55","nameEn":"Articulating Paper Blue – Full mouth (40 sheets/book, 6 books/box)","needsReview":false},
  {"sku":"07-11-56","nameEn":"Articulating Paper Red/Blue – Full mouth (12 sheets/book, 6 books/box)","needsReview":false},
  {"sku":"07-11-57","nameEn":"Articulating Paper Red – Half mouth (40 sheets/book, 10 books/box)","needsReview":false},
  {"sku":"07-11-58","nameEn":"Articulating Paper Blue – Half mouth (40 sheets/book, 10 books/box)","needsReview":false},
  {"sku":"07-11-59","nameEn":"Articulating Paper Red/Blue – Half mouth (12 sheets/book, 10 books/box)","needsReview":false},
  {"sku":"07-11-63","nameEn":"Face Shield – Plastic (10 pcs)","needsReview":false},
  {"sku":"07-14-10","nameEn":"Retraction Cord","needsReview":true},
  {"sku":"07-14-11","nameEn":"Retraction Cord","needsReview":true},
  {"sku":"07-14-12","nameEn":"Retraction Cord","needsReview":true},
  {"sku":"07-14-13","nameEn":"Retraction Cord","needsReview":true},
  {"sku":"07-14-14","nameEn":"Retraction Cord","needsReview":true},
  {"sku":"07-14-15","nameEn":"Retraction Cord","needsReview":true},
  {"sku":"07-15-00","nameEn":"Double Check Bite Foil – Double blue","needsReview":true},
  {"sku":"07-15-03","nameEn":"Shimstock Foil","needsReview":false},
  {"sku":"07-15-13","nameEn":"Stainless Dental Photo Mirror (No.3)","needsReview":false},
  {"sku":"07-15-14","nameEn":"Stainless Dental Photo Mirror (No.4)","needsReview":false},
  {"sku":"07-15-15","nameEn":"Stainless Dental Photo Mirror (No.5)","needsReview":false},
  {"sku":"07-15-23","nameEn":"Stainless Dental Photo Mirror (No.13)","needsReview":false},
  {"sku":"07-15-44","nameEn":"Cheek Retractor – With handles","needsReview":true},
  {"sku":"07-15-45","nameEn":"Cheek Retractor – With handles","needsReview":true},
  {"sku":"07-15-46","nameEn":"Double Head Lip Retractor","needsReview":true},
  {"sku":"07-15-47","nameEn":"Double Head Lip Retractor","needsReview":true},
  {"sku":"07-15-50","nameEn":"Stainless Steel Mouth Retractor","needsReview":false},
  {"sku":"07-15-51","nameEn":"Dental Mouth Opener with Aerosol Suction","needsReview":false},
  {"sku":"07-15-52","nameEn":"Carving Tooth Partner","needsReview":false},
  {"sku":"07-15-53","nameEn":"Instrument Gold","needsReview":true},
  {"sku":"07-15-58","nameEn":"Dental Finishing Polishing Strips","needsReview":true},
  {"sku":"07-15-59","nameEn":"Dental Finishing Polishing Strips","needsReview":true},
  {"sku":"07-15-60","nameEn":"Dental Finishing Polishing Strips","needsReview":true},
  {"sku":"07-15-61","nameEn":"Magnetic Retainer Box","needsReview":true},
  {"sku":"07-15-62","nameEn":"Magnetic Retainer Box","needsReview":true},
  {"sku":"07-15-63","nameEn":"Magnetic Retainer Box","needsReview":true},
  {"sku":"07-15-64","nameEn":"Magnetic Retainer Box","needsReview":true},
  {"sku":"07-15-65","nameEn":"Magnetic Retainer Box","needsReview":true},
  {"sku":"07-15-66","nameEn":"Dental Cotton Roll – Size S (8×38 cm)","needsReview":false},
  {"sku":"07-15-67","nameEn":"Dental Cotton Roll – Size M (10×38 cm)","needsReview":false},
  {"sku":"07-15-70","nameEn":"Bite Mixed","needsReview":true},
  {"sku":"07-15-71","nameEn":"Bite Mixed","needsReview":true},
  {"sku":"07-15-72","nameEn":"Bite Mixed","needsReview":true},
  {"sku":"07-15-73","nameEn":"Bite Mixed","needsReview":true},
  {"sku":"07-15-74","nameEn":"Bite Mixed","needsReview":true},
  {"sku":"07-15-75","nameEn":"Accessory Set","needsReview":true},
  {"sku":"07-15-76","nameEn":"Accessory Set","needsReview":true},
  {"sku":"07-15-77","nameEn":"Accessory Set","needsReview":true},
  {"sku":"07-15-78","nameEn":"Accessory Set","needsReview":true},
  {"sku":"07-16-25","nameEn":"Tooth Box","needsReview":true},
  {"sku":"07-16-26","nameEn":"Tooth Box","needsReview":true},
  {"sku":"07-16-27","nameEn":"Kids Milk Teeth Box – Green","needsReview":false},
  {"sku":"07-16-28","nameEn":"Kids Milk Teeth Box – White","needsReview":false},
  {"sku":"07-16-29","nameEn":"Kids Milk Teeth Box – Purple","needsReview":false},
  {"sku":"07-16-30","nameEn":"Kids Milk Teeth Box – Blue","needsReview":false},
  {"sku":"07-16-31","nameEn":"Kids Milk Teeth Box – Pink","needsReview":false},
  {"sku":"07-17-03","nameEn":"Sealing Sterilization Pouch (5 cm / 2 in × 200 m)","needsReview":false},
  {"sku":"07-17-04","nameEn":"Sealing Sterilization Pouch (7.5 cm / 3 in × 200 m)","needsReview":false},
  {"sku":"07-17-05","nameEn":"Sealing Sterilization Pouch (10 cm / 4 in × 200 m)","needsReview":false},
  {"sku":"07-17-06","nameEn":"Sealing Sterilization Pouch (15 cm / 6 in × 200 m)","needsReview":false},
  {"sku":"07-17-07","nameEn":"Sealing Sterilization Pouch (20 cm / 8 in × 200 m)","needsReview":false},
  {"sku":"07-17-08","nameEn":"Sealing Machine","needsReview":false},
  {"sku":"07-17-09","nameEn":"Protective Box Film","needsReview":true},
  {"sku":"07-17-10","nameEn":"Sterilization Tape (1.9 cm × 50 m)","needsReview":false},
  {"sku":"07-17-11","nameEn":"Sterilization Tape (1.2 cm × 50 m)","needsReview":false},
  {"sku":"07-17-12","nameEn":"Sealing Sterilization Pouch (25 cm / 10 in × 200 m)","needsReview":false},
  {"sku":"07-17-13","nameEn":"UV Hand Shield Protector","needsReview":false},
  {"sku":"07-17-22","nameEn":"Disposable Prophy Angles","needsReview":false},
  {"sku":"07-18-00","nameEn":"VRN-A8","needsReview":true},
  {"sku":"07-20-03","nameEn":"Kerr Regular Set Life","needsReview":true},
  {"sku":"07-20-05","nameEn":"Super Clean Spray (1,000 ml)","needsReview":false},
  {"sku":"07-20-06","nameEn":"Super Clean Spray (550 ml)","needsReview":false},
  {"sku":"07-21-04","nameEn":"Apex Locator","needsReview":false},
  {"sku":"07-22-01","nameEn":"Gutta Percha Points","needsReview":true},
  {"sku":"07-22-03","nameEn":"Gutta Percha Points","needsReview":true},
  {"sku":"07-22-04","nameEn":"Gutta Percha Points","needsReview":true},
  {"sku":"07-22-05","nameEn":"Gutta Percha Points","needsReview":true},
  {"sku":"07-22-06","nameEn":"Gutta Percha Points","needsReview":true},
  {"sku":"07-22-08","nameEn":"Gutta Percha Points","needsReview":true},
  {"sku":"07-22-09","nameEn":"Gutta Percha Points","needsReview":true},
  {"sku":"07-22-10","nameEn":"Gutta Percha Points","needsReview":true},
  {"sku":"07-22-11","nameEn":"Gutta Percha Points","needsReview":true},
  {"sku":"07-22-12","nameEn":"Gutta Percha Points","needsReview":true},
  {"sku":"07-22-13","nameEn":"Gutta Percha Points","needsReview":true},
  {"sku":"07-23-01","nameEn":"Paper Point","needsReview":true},
  {"sku":"07-23-02","nameEn":"Paper Point","needsReview":true},
  {"sku":"07-23-03","nameEn":"Paper Point","needsReview":true},
  {"sku":"07-23-04","nameEn":"Paper Point","needsReview":true},
  {"sku":"07-23-05","nameEn":"Paper Point","needsReview":true},
  {"sku":"07-31-01","nameEn":"Rubber Cup Holder","needsReview":true},
  {"sku":"07-31-02","nameEn":"Prophy Brush with Handle #6","needsReview":false},
  {"sku":"07-31-03","nameEn":"CBS Polishing Brush","needsReview":false},
  {"sku":"07-32-01","nameEn":"Dental Mixing Tips","needsReview":false},
  {"sku":"07-32-02","nameEn":"Intra-oral Tips – Yellow","needsReview":false},
  {"sku":"07-45-12","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-45-13","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-45-14","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-45-15","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-45-16","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-45-17","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-45-18","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-45-19","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-45-20","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-45-21","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-45-22","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-45-23","nameEn":"Mani Surgical Needles","needsReview":true},
  {"sku":"07-51-15","nameEn":"Leone Hard/Soft – Aligner Sheets (120 mm, 2 mm)","needsReview":false},
  {"sku":"07-51-16","nameEn":"Leone Hard/Soft – Aligner Sheets (120 mm, 3 mm)","needsReview":false},
  {"sku":"07-51-17","nameEn":"Leone Hard/Soft – Aligner Sheets (125 mm, 2 mm)","needsReview":false},
  {"sku":"07-51-27","nameEn":"Copolymer Dental Plates (2 mm)","needsReview":false},
  {"sku":"07-51-28","nameEn":"Copolymer Dental Plates (3 mm)","needsReview":false},
  {"sku":"07-61-03","nameEn":"Tongue/Gingiva Depressor TM-085","needsReview":true},
  {"sku":"07-61-40","nameEn":"Orthodontic Ring Box – Large","needsReview":false},
  {"sku":"07-61-41","nameEn":"Orthodontic Ring Box – 18 holes","needsReview":false},
  {"sku":"07-64-40","nameEn":"Megatray Color Transparent","needsReview":true},
  {"sku":"07-64-68","nameEn":"Megatray Color Transparent","needsReview":true},
  {"sku":"07-65-71","nameEn":"Diamond Burs RA BR-R45","needsReview":false},
  {"sku":"07-65-72","nameEn":"Diamond Burs RA BR-R46","needsReview":false},
  {"sku":"07-65-73","nameEn":"Diamond Burs RA BR-R41","needsReview":false},
  {"sku":"07-65-74","nameEn":"Diamond Burs RA BR-R40","needsReview":false},
  {"sku":"07-65-75","nameEn":"Diamond Burs RA BR-R26","needsReview":false},
  {"sku":"07-66-01","nameEn":"Diamond Burs FG TF-11","needsReview":false},
  {"sku":"07-66-02","nameEn":"Diamond Burs FG TF-12","needsReview":false},
  {"sku":"07-66-03","nameEn":"Diamond Burs FG TF-13","needsReview":false},
  {"sku":"07-66-04","nameEn":"Diamond Burs FG TF-14","needsReview":false},
  {"sku":"07-66-05","nameEn":"Diamond Burs FG TF-20","needsReview":false},
  {"sku":"07-66-06","nameEn":"Diamond Burs FG TF-21","needsReview":false},
  {"sku":"07-66-07","nameEn":"Diamond Burs FG TF-22","needsReview":false},
  {"sku":"07-66-08","nameEn":"Diamond Burs FG TF-23","needsReview":false},
  {"sku":"07-66-09","nameEn":"Diamond Burs FG TF-31","needsReview":false},
  {"sku":"07-66-10","nameEn":"Diamond Burs FG TF-41","needsReview":false},
  {"sku":"07-66-17","nameEn":"Diamond Burs FG FO-30EF","needsReview":false},
  {"sku":"07-66-18","nameEn":"Diamond Burs FG TF-13C","needsReview":false},
  {"sku":"07-66-19","nameEn":"Diamond Burs FG TF-12F","needsReview":false},
  {"sku":"07-66-20","nameEn":"Diamond Burs FG TF-21F","needsReview":false},
  {"sku":"07-66-23","nameEn":"Diamond Burs FG TR-11","needsReview":false},
  {"sku":"07-66-24","nameEn":"Diamond Burs FG TR-12","needsReview":false},
  {"sku":"07-66-25","nameEn":"Diamond Burs FG TR-13","needsReview":false},
  {"sku":"07-66-26","nameEn":"Diamond Burs FG TR-15","needsReview":false},
  {"sku":"07-66-27","nameEn":"Diamond Burs FG TR-19","needsReview":false},
  {"sku":"07-66-28","nameEn":"Diamond Burs FG TR-20","needsReview":false},
  {"sku":"07-66-29","nameEn":"Diamond Burs FG TR-21","needsReview":false},
  {"sku":"07-66-30","nameEn":"Diamond Burs FG TR-24","needsReview":false},
  {"sku":"07-66-31","nameEn":"Diamond Burs FG TR-25","needsReview":false},
  {"sku":"07-66-38","nameEn":"Diamond Burs FG TR-21F","needsReview":false},
  {"sku":"07-66-39","nameEn":"Diamond Burs FG TR-20F","needsReview":false},
  {"sku":"07-66-40","nameEn":"Diamond Burs FG TR-62F","needsReview":false},
  {"sku":"07-66-41","nameEn":"Diamond Burs FG TR-11EF","needsReview":false},
  {"sku":"07-66-46","nameEn":"Diamond Burs FG TC-11","needsReview":false},
  {"sku":"07-66-47","nameEn":"Diamond Burs FG TC-21","needsReview":false},
  {"sku":"07-66-50","nameEn":"Diamond Burs FG TC-11F","needsReview":false},
  {"sku":"07-66-51","nameEn":"Diamond Burs FG TC-21F","needsReview":false},
  {"sku":"07-66-52","nameEn":"Diamond Burs FG FO-11","needsReview":false},
  {"sku":"07-66-53","nameEn":"Diamond Burs FG FO-22","needsReview":false},
  {"sku":"07-66-54","nameEn":"Diamond Burs FG FO-27","needsReview":false},
  {"sku":"07-66-55","nameEn":"Diamond Burs FG FO-32","needsReview":false},
  {"sku":"07-66-57","nameEn":"Diamond Burs FG FO-54C","needsReview":false},
  {"sku":"07-66-59","nameEn":"Diamond Burs FG FO-22F","needsReview":false},
  {"sku":"07-66-63","nameEn":"Diamond Burs FG FO-30F","needsReview":false},
  {"sku":"07-66-64","nameEn":"Diamond Burs FG FO-20EF","needsReview":false},
  {"sku":"07-66-68","nameEn":"Diamond Burs FG SF-11","needsReview":false},
  {"sku":"07-66-69","nameEn":"Diamond Burs FG SF-12","needsReview":false},
  {"sku":"07-66-70","nameEn":"Diamond Burs FG SF-13","needsReview":false},
  {"sku":"07-66-71","nameEn":"Diamond Burs FG SF-21","needsReview":false},
  {"sku":"07-66-73","nameEn":"Diamond Burs FG SF-12C","needsReview":false},
  {"sku":"07-66-74","nameEn":"Diamond Burs FG SO-20","needsReview":false},
  {"sku":"07-66-75","nameEn":"Diamond Burs FG SO-21","needsReview":false},
  {"sku":"07-66-77","nameEn":"Diamond Burs FG SR-12","needsReview":false},
  {"sku":"07-66-78","nameEn":"Diamond Burs FG SR-13","needsReview":false},
  {"sku":"07-66-80","nameEn":"Diamond Burs FG EX-12","needsReview":false},
  {"sku":"07-66-81","nameEn":"Diamond Burs FG EX-20","needsReview":false},
  {"sku":"07-66-82","nameEn":"Diamond Burs FG EX-21","needsReview":false},
  {"sku":"07-66-84","nameEn":"Diamond Burs FG EX-26","needsReview":false},
  {"sku":"07-66-87","nameEn":"Diamond Burs FG EX-18F","needsReview":false},
  {"sku":"07-66-88","nameEn":"Diamond Burs FG EX-21F","needsReview":false},
  {"sku":"07-66-90","nameEn":"Diamond Burs FG BR-40","needsReview":false},
  {"sku":"07-66-91","nameEn":"Diamond Burs FG BR-45","needsReview":false},
  {"sku":"07-66-92","nameEn":"Diamond Burs FG BR-46","needsReview":false},
  {"sku":"07-66-96","nameEn":"Diamond Burs FG BR-31C","needsReview":false},
  {"sku":"07-66-98","nameEn":"Diamond Burs FG BR-40EF","needsReview":false},
  {"sku":"07-66-99","nameEn":"Diamond Burs FG BC-31","needsReview":false},
  {"sku":"07-67-00","nameEn":"Diamond Burs FG EX-18","needsReview":false},
  {"sku":"07-67-01","nameEn":"Diamond Burs FG BC-42","needsReview":false},
  {"sku":"07-67-10","nameEn":"Diamond Burs FG CD-55F","needsReview":false},
  {"sku":"07-67-23","nameEn":"Diamond Burs FG SI-46","needsReview":false},
  {"sku":"07-67-24","nameEn":"Diamond Burs FG SI-47","needsReview":false},
  {"sku":"07-67-25","nameEn":"Diamond Burs FG SI-48","needsReview":false},
  {"sku":"07-67-27","nameEn":"Diamond Burs FG SI-548","needsReview":false},
  {"sku":"07-67-31","nameEn":"Diamond Burs FG WR-13","needsReview":false},
  {"sku":"07-67-35","nameEn":"Diamond Burs FG FO-21","needsReview":false},
  {"sku":"07-67-36","nameEn":"Diamond Burs FG FO-25","needsReview":false},
  {"sku":"07-67-38","nameEn":"Diamond Burs FG SR-11","needsReview":false},
  {"sku":"07-67-39","nameEn":"Diamond Burs FG BR-31","needsReview":false},
  {"sku":"07-67-40","nameEn":"Diamond Burs FG BR-41","needsReview":false},
  {"sku":"07-67-41","nameEn":"Diamond Burs FG TR-13C","needsReview":false},
  {"sku":"07-67-42","nameEn":"Diamond Burs FG TR-62C","needsReview":false},
  {"sku":"07-67-44","nameEn":"Diamond Burs FG TC-21EF","needsReview":false},
  {"sku":"07-67-45","nameEn":"Diamond Burs FG TF-S23","needsReview":false},
  {"sku":"07-67-46","nameEn":"Diamond Burs FG SI-R46","needsReview":false},
  {"sku":"07-67-47","nameEn":"Diamond Burs FG TR-24EF","needsReview":false},
  {"sku":"07-67-50","nameEn":"Diamond Burs FG SR-41","needsReview":false},
  {"sku":"07-67-51","nameEn":"Diamond Burs FG SR-42","needsReview":false},
  {"sku":"07-67-52","nameEn":"Diamond Burs FG SR-21","needsReview":false},
  {"sku":"07-67-54","nameEn":"Diamond Burs FG TC-10","needsReview":false},
  {"sku":"07-67-68","nameEn":"Diamond Burs FG TR-62","needsReview":false},
  {"sku":"07-67-71","nameEn":"Diamond Burs FG TR-14","needsReview":false},
  {"sku":"07-67-74","nameEn":"Diamond Burs FG FO-41","needsReview":false},
  {"sku":"07-67-76","nameEn":"Diamond Burs FG FO-34","needsReview":false},
  {"sku":"07-67-77","nameEn":"Diamond Burs FG TR-22","needsReview":false},
  {"sku":"07-67-78","nameEn":"Diamond Burs FG TR-28","needsReview":false},
  {"sku":"07-67-80","nameEn":"Diamond Burs FG WR-48","needsReview":false},
  {"sku":"07-67-82","nameEn":"Diamond Burs FG BC-11","needsReview":false},
  {"sku":"07-67-89","nameEn":"Diamond Burs FG EX-11S","needsReview":false},
  {"sku":"07-67-90","nameEn":"Diamond Burs FG EX-12S","needsReview":false},
  {"sku":"07-67-91","nameEn":"Diamond Burs FG SF-31S","needsReview":false},
  {"sku":"07-67-94","nameEn":"Diamond Burs FG SF-13S","needsReview":false},
  {"sku":"07-67-95","nameEn":"Diamond Burs FG TR-22S","needsReview":false},
  {"sku":"07-68-02","nameEn":"Diamond Burs FG FO-13","needsReview":false},
  {"sku":"07-68-07","nameEn":"Diamond Burs FG 879K16","needsReview":false},
  {"sku":"07-68-08","nameEn":"H-Files (Long 21 mm)","needsReview":true},
  {"sku":"07-68-10","nameEn":"H-Files (Long 21 mm)","needsReview":true},
  {"sku":"07-68-15","nameEn":"H-Files (Long 21 mm)","needsReview":true},
  {"sku":"07-68-20","nameEn":"H-Files (Long 21 mm)","needsReview":true},
  {"sku":"07-68-41","nameEn":"H-Files (Long 21 mm)","needsReview":true},
  {"sku":"07-69-08","nameEn":"H-Files (Long 25 mm)","needsReview":true},
  {"sku":"07-69-10","nameEn":"H-Files (Long 25 mm)","needsReview":true},
  {"sku":"07-69-15","nameEn":"H-Files (Long 25 mm)","needsReview":true},
  {"sku":"07-69-20","nameEn":"H-Files (Long 25 mm)","needsReview":true},
  {"sku":"07-69-41","nameEn":"H-Files (Long 25 mm)","needsReview":true},
  {"sku":"07-70-06","nameEn":"K-Files – 21 mm","needsReview":false},
  {"sku":"07-70-08","nameEn":"K-Files – 21 mm","needsReview":false},
  {"sku":"07-70-10","nameEn":"K-Files – 21 mm","needsReview":false},
  {"sku":"07-70-15","nameEn":"K-Files – 21 mm","needsReview":false},
  {"sku":"07-70-20","nameEn":"K-Files – 21 mm","needsReview":false},
  {"sku":"07-70-30","nameEn":"K-Files – 21 mm","needsReview":false},
  {"sku":"07-70-35","nameEn":"K-Files – 21 mm","needsReview":false},
  {"sku":"07-70-40","nameEn":"K-Files – 21 mm","needsReview":false},
  {"sku":"07-70-41","nameEn":"K-Files – 21 mm","needsReview":false},
  {"sku":"07-71-06","nameEn":"K-Files – 25 mm","needsReview":false},
  {"sku":"07-71-08","nameEn":"K-Files – 25 mm","needsReview":false},
  {"sku":"07-71-10","nameEn":"K-Files – 25 mm","needsReview":false},
  {"sku":"07-71-15","nameEn":"K-Files – 25 mm","needsReview":false},
  {"sku":"07-71-20","nameEn":"K-Files – 25 mm","needsReview":false},
  {"sku":"07-71-35","nameEn":"K-Files – 25 mm","needsReview":false},
  {"sku":"07-71-41","nameEn":"K-Files – 25 mm","needsReview":false},
  {"sku":"07-71-81","nameEn":"K-Files – 25 mm","needsReview":false},
  {"sku":"07-72-25","nameEn":"Paste Carriers – 21 mm","needsReview":false},
  {"sku":"07-72-30","nameEn":"Paste Carriers – 21 mm","needsReview":false},
  {"sku":"07-72-35","nameEn":"Paste Carriers – 21 mm","needsReview":false},
  {"sku":"07-72-40","nameEn":"Paste Carriers – 21 mm","needsReview":false},
  {"sku":"07-72-41","nameEn":"Paste Carriers – 21 mm","needsReview":false},
  {"sku":"07-73-25","nameEn":"Paste Carriers – 25 mm","needsReview":false},
  {"sku":"07-73-30","nameEn":"Paste Carriers – 25 mm","needsReview":false},
  {"sku":"07-73-35","nameEn":"Paste Carriers – 25 mm","needsReview":false},
  {"sku":"07-73-40","nameEn":"Paste Carriers – 25 mm","needsReview":false},
  {"sku":"07-73-41","nameEn":"Paste Carriers – 25 mm","needsReview":false},
  {"sku":"07-74-01","nameEn":"Peeso Reamers – 28 mm","needsReview":false},
  {"sku":"07-74-02","nameEn":"Peeso Reamers – 28 mm","needsReview":false},
  {"sku":"07-74-03","nameEn":"Peeso Reamers – 28 mm","needsReview":false},
  {"sku":"07-75-01","nameEn":"Peeso Reamers – 32 mm","needsReview":false},
  {"sku":"07-75-02","nameEn":"Peeso Reamers – 32 mm","needsReview":false},
  {"sku":"07-75-03","nameEn":"Peeso Reamers – 32 mm","needsReview":false},
  {"sku":"07-76-01","nameEn":"Gates Drills-G – 28 mm","needsReview":false},
  {"sku":"07-76-02","nameEn":"Gates Drills-G – 28 mm","needsReview":false},
  {"sku":"07-76-03","nameEn":"Gates Drills-G – 28 mm","needsReview":false},
  {"sku":"07-77-01","nameEn":"Gates Drills-G – 32 mm","needsReview":false},
  {"sku":"07-77-02","nameEn":"Gates Drills-G – 32 mm","needsReview":false},
  {"sku":"07-77-03","nameEn":"Gates Drills-G – 32 mm","needsReview":false},
  {"sku":"08-03-01","nameEn":"Ultrasonic Cleaner – 2 L","needsReview":false},
  {"sku":"08-03-02","nameEn":"Ultrasonic Cleaner – 2.5 L","needsReview":false},
  {"sku":"08-03-06","nameEn":"Dental Mobile Light","needsReview":false},
  {"sku":"08-04-06","nameEn":"Micromotor N7","needsReview":false},
  {"sku":"08-04-08","nameEn":"SDE-E35 Straight Handpiece","needsReview":false},
  {"sku":"08-04-09","nameEn":"SP-CE Contra Angle","needsReview":false},
  {"sku":"08-04-61","nameEn":"Yamabishi Polishing Lathe","needsReview":true},
  {"sku":"08-04-73","nameEn":"Dental Handpiece Cleaning & Lubrication Unit","needsReview":false},
  {"sku":"08-04-74","nameEn":"M-Kong Dust Collector","needsReview":false},
  {"sku":"08-05-04","nameEn":"Marathon Multi 600","needsReview":false},
  {"sku":"08-05-39","nameEn":"Rolence Tray LED","needsReview":false},
  {"sku":"08-06-01","nameEn":"SDE-H37L1 Handpiece","needsReview":false},
  {"sku":"08-06-02","nameEn":"SDE-H35SPI Handpiece","needsReview":false},
  {"sku":"08-06-03","nameEn":"SM45C Handpiece","needsReview":false},
  {"sku":"08-06-04","nameEn":"SDE-BM50SI Handpiece","needsReview":false},
  {"sku":"08-06-05","nameEn":"SDE-B55OC Handpiece","needsReview":false},
  {"sku":"08-06-06","nameEn":"SDE-M35Es Handpiece – E-type","needsReview":false},
  {"sku":"08-06-07","nameEn":"SDE-M40Es Handpiece – E-type","needsReview":false},
  {"sku":"08-06-08","nameEn":"Micromotor Champion","needsReview":false},
  {"sku":"08-06-16","nameEn":"Micromotor Foot Switch","needsReview":false},
  {"sku":"08-08-04","nameEn":"Plaster","needsReview":false},
  {"sku":"08-08-12","nameEn":"Ortho Plaster","needsReview":false},
  {"sku":"08-08-13","nameEn":"Ortho Plaster","needsReview":false},
  {"sku":"08-08-15","nameEn":"Plaster","needsReview":false},
  {"sku":"08-09-00","nameEn":"Articulator – Small","needsReview":false},
  {"sku":"08-09-02","nameEn":"Flask – 5 inch","needsReview":false},
  {"sku":"08-09-03","nameEn":"Flask – 6 inch","needsReview":false},
  {"sku":"08-09-04","nameEn":"Duplicating Flask","needsReview":false},
  {"sku":"08-09-06","nameEn":"Flask Clamp Denture","needsReview":false},
  {"sku":"08-09-16","nameEn":"Injection Flask – Oval (22 mm)","needsReview":false},
  {"sku":"08-09-17","nameEn":"Injection Flask – Oval (25 mm)","needsReview":false},
  {"sku":"08-09-20","nameEn":"Injection Flask – Bipol (22 mm)","needsReview":true},
  {"sku":"08-09-21","nameEn":"Injection Flask – Bipol (25 mm)","needsReview":true},
  {"sku":"08-09-22","nameEn":"Articulator – Big","needsReview":false},
  {"sku":"08-11-00","nameEn":"Alcohol Torch","needsReview":false},
  {"sku":"08-18-03","nameEn":"Tray – Full arch (No.3)","needsReview":false},
  {"sku":"08-19-11","nameEn":"Impression Trays – Heat-expandable (No.1, 2)","needsReview":false},
  {"sku":"08-19-12","nameEn":"Impression Trays – Heat-expandable (No.3, 4)","needsReview":false},
  {"sku":"08-19-14","nameEn":"Impression Trays – Heat-expandable (No.7, 8)","needsReview":false},
  {"sku":"08-19-15","nameEn":"Impression Trays – Heat-expandable (No.9, 10)","needsReview":false},
  {"sku":"08-19-31","nameEn":"Tray – Non-perforated","needsReview":true},
  {"sku":"08-19-32","nameEn":"Tray – Non-perforated","needsReview":true},
  {"sku":"08-19-33","nameEn":"Tray – Non-perforated","needsReview":true},
  {"sku":"08-19-34","nameEn":"Tray – Non-perforated","needsReview":true},
  {"sku":"08-19-35","nameEn":"Tray – Non-perforated","needsReview":true},
  {"sku":"08-19-36","nameEn":"Tray – Non-perforated","needsReview":true},
  {"sku":"08-19-37","nameEn":"Tray – Non-perforated","needsReview":true},
  {"sku":"08-19-38","nameEn":"Tray – Non-perforated","needsReview":true},
  {"sku":"08-19-39","nameEn":"Tray – Non-perforated","needsReview":true},
  {"sku":"08-19-40","nameEn":"Tray – Non-perforated","needsReview":true},
  {"sku":"08-19-41","nameEn":"Tray – Perforated","needsReview":true},
  {"sku":"08-19-42","nameEn":"Tray – Perforated","needsReview":true},
  {"sku":"08-19-43","nameEn":"Tray – Perforated","needsReview":true},
  {"sku":"08-19-44","nameEn":"Tray – Perforated","needsReview":true},
  {"sku":"08-19-45","nameEn":"Tray – Perforated","needsReview":true},
  {"sku":"08-19-46","nameEn":"Tray – Perforated","needsReview":true},
  {"sku":"08-19-47","nameEn":"Tray – Perforated","needsReview":true},
  {"sku":"08-19-48","nameEn":"Tray – Perforated","needsReview":true},
  {"sku":"08-19-49","nameEn":"Tray – Perforated","needsReview":true},
  {"sku":"08-19-50","nameEn":"Tray – Perforated","needsReview":true},
  {"sku":"08-26-01","nameEn":"Articulator ASA-1500","needsReview":false},
  {"sku":"08-35-00","nameEn":"Surveyor Marathon-103","needsReview":false},
  {"sku":"09-01-02","nameEn":"Major Dent","needsReview":true},
  {"sku":"16-00-01","nameEn":"AESUB Scanning Spray","needsReview":false},
  {"sku":"16-00-30","nameEn":"ONE Intraoral Sensor Direct USB #1","needsReview":false},
  {"sku":"16-00-31","nameEn":"ONE Intraoral Sensor Direct USB #2","needsReview":false},
  {"sku":"16-00-39","nameEn":"Owandy I-Max Pro Digital Pan with Ceph Arm – 2 sensors","needsReview":false},
  {"sku":"16-00-44","nameEn":"Owandy I-Max 3D Pro Ceph (CBCT Conebeam & Panoramic & Cephalometric) – 2 sensors / 3-in-1","needsReview":false},
  {"sku":"19-01-02","nameEn":"Major Dent","needsReview":true},
  {"sku":"20-09-01","nameEn":"Vaseline (1 kg)","needsReview":false},
  {"sku":"20-09-02","nameEn":"Vaseline (500 g)","needsReview":false},
  {"sku":"90-00-00","nameEn":"Major Plus","needsReview":true},
  {"sku":"91-00-00","nameEn":"Major Plus","needsReview":true},
];
