// Typed API client for the Venus CRM UI. Talks to the SHARED Minerva Fastify backend
// (the /api/venus/* routes) — see api/src/routes/venus.ts + docs/VENUS_BRIEF.md.
// Venus is track-and-tell only; Stage C (this app) wires login + the customer-master
// screens Stage A+B already built. Sales/analytics are not wired yet (Phase 1/2).

export const API_URL: string = import.meta.env.VITE_API_URL ?? 'http://localhost:3000';

// Access to Venus is per-grant, enforced server-side via requireApp('venus') (see
// api/src/routes/venus.ts): supervisor always has access; employees need the explicit
// 'venus' grant (Agent.apps); md is excluded. The login screen does not hard-block by
// role — an ungranted employee logs in fine and gets a friendly 403 state instead (App.tsx).
export type Role = 'supervisor' | 'md' | 'employee';
export interface Agent {
  id: string;
  email: string;
  name: string;
  role: Role;
}

// Mirrors the VenusCustomer Prisma model (api/prisma/schema.prisma) field-for-field.
export interface VenusCustomer {
  code: string;
  searchKey: string;
  name: string;
  nameEn: string | null;
  custType: string | null;
  repCode: string | null;
  zone: string | null;
  priceType: string | null;
  discount: string | null;
  address: string | null;
  contact: string | null;
  phone: string | null;
  acctNo: string | null;
  shipBy: string | null;
  creditDays: number | null;
  creditLimit: string | null;
  creditTerms: string | null;
  creditTermsNorm: 'CASH' | 'PREPAY' | 'CREDIT' | 'OTHER' | null;
  note: string | null;
  importedAt: string;
}

// The 5 Thai RFM segments (VENUS_BRIEF.md §6). Order here = display/severity order used
// across the dashboard and segment chips.
export type Segment = 'ลูกค้าชั้นดี' | 'ลูกค้าประจำ' | 'มาใหม่' | 'เสี่ยงหาย' | 'หายไปแล้ว';
export const SEGMENTS: Segment[] = ['ลูกค้าชั้นดี', 'ลูกค้าประจำ', 'มาใหม่', 'เสี่ยงหาย', 'หายไปแล้ว'];

// List rows are enriched with a left-joined CustomerStats sliver (segment + M) — see
// GET /api/venus/customers in api/src/routes/venus.ts.
export interface VenusCustomerListRow extends VenusCustomer {
  segment: Segment | null;
  m: number | null;
}

// Mirrors CustomerStats (api/prisma/schema.prisma) field-for-field.
export interface ReorderDueItem {
  sku: string;
  name: string | null;
  lastPurchase: string;
  medianGapDays: number;
  dueSinceDays: number;
  purchaseCount: number;
}
// Cross-sell gap (VENUS_BRIEF.md §7): a learned bought-together pairing (CrossSellLink) the
// customer owns the anchor for but has never bought the paired crossSku.
export interface CrossSellGapItem {
  crossSku: string;
  name: string | null;
  anchorSku: string;
  score: number;
}
// Big-ticket anniversary (VENUS_BRIEF.md §6/§7): a one-off equipment purchase aged enough to
// be worth a service/upgrade-timing nudge.
export interface BigTicketItem {
  sku: string;
  name: string | null;
  unitPrice: number;
  monthsAgo: number;
  lastPurchase: string;
}
export interface CustomerStats {
  customerCode: string;
  r: number | null;
  f: number | null;
  m: number | null;
  rfmScore: string | null;
  segment: Segment | null;
  trendPct: number | null;
  trendDir: 'up' | 'down' | 'flat' | null;
  trendOrders: number | null;
  reorderDue: ReorderDueItem[] | null;
  crossSellGaps: CrossSellGapItem[] | null;
  bigTicket: BigTicketItem[] | null;
  dataFrom: string | null;
  dataTo: string | null;
  computedAt: string;
}

export interface PurchaseLine {
  sku: string | null;
  name: string | null;
  qty: number;
  unit: string | null;
  amount: number;
}
export interface Purchase {
  docNo: string;
  date: string;
  total: number;
  docType: string | null;
  void: boolean;
  lines: PurchaseLine[];
}
export interface ProductCycle {
  sku: string;
  name: string | null;
  count: number;
  totalQty: number;
  lastPurchase: string;
  reorderStatus: 'due' | 'ok';
  reorderDue: ReorderDueItem | null;
}
export interface CustomerNote {
  text: string;
  authorName: string | null;
  updatedAt: string;
}
export interface CustomerPrecautions {
  credit: string | null;
  payment: string | null;
  churn: string | null;
  complaints: string | null;
  note: CustomerNote | null;
}
// Weekly AI suggestion card (VENUS_BRIEF.md §7, Phase 3 stage 2). Read-only from the UI's
// point of view — the card is generated by the batch script (venus-generate-cards.ts), never
// by opening this screen. Null when the customer has no active signal (or the batch hasn't
// run / had no LLM key yet) — in that case the UI shows nothing extra, the rules badges in
// the ภาพรวม tab already carry the signal information.
export interface AiCard {
  text: string;
  createdAt: string;
}
export interface CustomerDetailResult {
  customer: VenusCustomer;
  stats: CustomerStats | null;
  purchases: Purchase[];
  productCycles: ProductCycle[];
  precautions: CustomerPrecautions;
  aiCard: AiCard | null;
}

// ── Management-lens dashboard ──────────────────────────────────────────────

export interface DashboardAtRiskRow {
  code: string;
  name: string;
  m: number;
  f: number;
  rfmScore: string | null;
  trendPct: number;
  trendDir: 'up' | 'down' | 'flat';
}
export interface DashboardMoverRow {
  code: string;
  name: string;
  m: number;
  trendPct: number;
  trendDir: 'up' | 'down' | 'flat';
  trendOrders: number;
}
export interface DashboardOpportunityRow {
  code: string;
  name: string;
  reorderDue: ReorderDueItem[];
  mostOverdue: number;
}
export interface DashboardResult {
  coverage: { from: string | null; to: string | null };
  segmentCounts: Partial<Record<Segment, number>>;
  totalCustomers: number;
  totalWithSales: number;
  atRisk: DashboardAtRiskRow[];
  topMovers: { up: DashboardMoverRow[]; down: DashboardMoverRow[] };
  opportunityQueue: DashboardOpportunityRow[];
}

export const getDashboard = () => authed<DashboardResult>('/api/venus/dashboard');

// Supervisor-only: recompute the RFM/segments/trend/reorder/signal engine over all sales.
// Synchronous + can take ~15–40s on a full base — the caller shows a spinner.
export interface RecomputeResult {
  ok: boolean;
  customersProcessed: number;
  segmentCounts: Record<string, number>;
}
export const recompute = () => authed<RecomputeResult>('/api/venus/recompute', { method: 'POST' });

// Supervisor-only: generate AI suggestion cards for the top-value flagged customers.
// Bounded (one LLM call each); fail-soft — no key on the server → written 0, skippedNoLlm>0.
export interface GenerateCardsResult {
  ok: boolean;
  candidates: number;
  written: number;
  skippedNoLlm: number;
  skippedError: number;
}
export const generateCards = (limit = 15) =>
  authed<GenerateCardsResult>('/api/venus/generate-cards', {
    method: 'POST',
    body: JSON.stringify({ limit }),
  });

const TOKEN_KEY = 'venus_token';
const AGENT_KEY = 'venus_agent';

export function getToken(): string | null {
  return localStorage.getItem(TOKEN_KEY);
}
export function getStoredAgent(): Agent | null {
  const s = localStorage.getItem(AGENT_KEY);
  if (!s) return null;
  try {
    return JSON.parse(s) as Agent;
  } catch {
    clearSession();
    return null;
  }
}
export function setSession(token: string, agent: Agent): void {
  localStorage.setItem(TOKEN_KEY, token);
  localStorage.setItem(AGENT_KEY, JSON.stringify(agent));
}
export function clearSession(): void {
  localStorage.removeItem(TOKEN_KEY);
  localStorage.removeItem(AGENT_KEY);
}

// Notified on a 401 (daily JWT expiry, or an account demoted/removed) so the app can drop
// back to Login instead of sitting as a dead husk of failed fetches. Set by App.tsx.
let onUnauthorized: (() => void) | null = null;
export function setOnUnauthorized(fn: (() => void) | null): void { onUnauthorized = fn; }

// Notified on a 403 (authenticated but WITHOUT the 'venus' grant — e.g. an employee the
// owner hasn't granted Venus yet). Distinct from 401: the session stays valid, we just show
// a friendly "no access" state rather than bouncing to Login (which they'd just pass again).
let onForbidden: (() => void) | null = null;
export function setOnForbidden(fn: (() => void) | null): void { onForbidden = fn; }

async function authed<T>(path: string, init?: RequestInit): Promise<T> {
  const token = getToken();
  const res = await fetch(`${API_URL}${path}`, {
    ...init,
    headers: {
      'content-type': 'application/json',
      ...(token ? { authorization: `Bearer ${token}` } : {}),
      ...(init?.headers ?? {}),
    },
  });
  if (res.status === 401) {
    clearSession();
    onUnauthorized?.();
    throw new Error('unauthorized');
  }
  if (res.status === 403) {
    onForbidden?.();
    throw new Error('forbidden');
  }
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json() as Promise<T>;
}

// Same shared login endpoint every service uses — any live account may authenticate here;
// per-app access is enforced server-side by requireApp('venus') on the app's own routes
// (api/src/routes/venus.ts): supervisor always has access, employees need the explicit
// 'venus' grant, md is excluded.
export async function login(email: string, password: string): Promise<{ token: string; agent: Agent }> {
  const res = await fetch(`${API_URL}/api/auth/login`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ email, password }),
  });
  if (!res.ok) throw new Error('invalid_credentials');
  return res.json() as Promise<{ token: string; agent: Agent }>;
}

export interface LoginName {
  email: string;
  name: string;
  kind: 'password' | 'pin';
}
// PUBLIC — no auth required. Ordered: supervisor first (kind 'password'), then any
// granted MD/employee cards. Uses the GENERAL suite endpoint (not an app-owned one like
// Ceres's /api/ceres/logins) since Venus access is grant-based, not role-based.
export const getLogins = () =>
  fetch(`${API_URL}/api/auth/logins?app=venus`).then((r) => {
    if (!r.ok) throw new Error('logins_failed');
    return r.json() as Promise<LoginName[]>;
  });

export const canImport = (agent: Agent | null): boolean => agent?.role === 'supervisor';

// ── Customers ────────────────────────────────────────────────────────────

export interface CustomerListResult {
  total: number;
  customers: VenusCustomerListRow[];
}

export const getCustomers = (params: { q?: string; limit?: number; offset?: number; segment?: Segment | '' }) => {
  const p = new URLSearchParams();
  if (params.q) p.set('q', params.q);
  if (params.segment) p.set('segment', params.segment);
  p.set('limit', String(params.limit ?? 50));
  p.set('offset', String(params.offset ?? 0));
  return authed<CustomerListResult>(`/api/venus/customers?${p.toString()}`);
};

export const getCustomer = (code: string) =>
  authed<CustomerDetailResult>(`/api/venus/customers/${encodeURIComponent(code)}`);

// Manual pinned note (precaution #4) — shared-pool write: any logged-in Venus user (not
// just supervisor) can save/clear it. Empty text clears the note server-side.
export const saveNote = (code: string, text: string) =>
  authed<{ ok: boolean; note: CustomerNote | null }>(`/api/venus/customers/${encodeURIComponent(code)}/note`, {
    method: 'PUT',
    body: JSON.stringify({ text }),
  });

// ── Import (supervisor only) — Express ARMAST customer-master preview→apply ─────

export interface ImportPreview {
  token: string;
  fileName: string;
  encoding: string;
  pageCount: number;
  parsedCount: number;
  matched: number;
  unmatched: number;
  typeBreakdown: Record<string, number>;
  creditBreakdown: Record<string, number>;
  unresolved: number;
  unresolvedSamples: string[];
}

export interface ImportApplyResult {
  ok: boolean;
  created: number;
  updated: number;
  unresolved: number;
  unresolvedSamples: string[];
}

// Reads a File as raw bytes, base64-encoded (no data: prefix) — the server sniffs the
// Thai text encoding itself (see decodeExpressBytes), so we must NOT let the browser
// decode it as text first.
export function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const buf = reader.result as ArrayBuffer;
      const bytes = new Uint8Array(buf);
      let binary = '';
      for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
      resolve(btoa(binary));
    };
    reader.onerror = () => reject(reader.error ?? new Error('read_failed'));
    reader.readAsArrayBuffer(file);
  });
}

export const previewCustomerImport = (dataB64: string, fileName: string) =>
  authed<ImportPreview>('/api/venus/import/customers', {
    method: 'POST',
    body: JSON.stringify({ mode: 'preview', dataB64, fileName }),
  });

// ── Sales import (OESOC — sales orders grouped by customer) ──────────────────
export interface SalesImportPreview {
  token: string;
  fileName: string;
  encoding: string;
  docs: number;
  lineItems: number;
  distinctCodes: number;
  matchedCodes: number;
  unmatchedCodes: number;
  unmatchedCodesSample: string[];
  voids: number;
  dateSpan: { min: string | null; max: string | null };
  selfCertify: { docChecked: number; docOk: number; custSubtotalChecked: number; custSubtotalOk: number };
  unresolved: number;
  unresolvedSamples: string[];
}
export interface SalesImportApplyResult {
  ok: boolean;
  docsCreated: number;
  docsUpdated: number;
  linesWritten: number;
  unmatchedCodes: string[];
  unresolved: number;
  unresolvedSamples: string[];
}
export const previewSalesImport = (dataB64: string, fileName: string) =>
  authed<SalesImportPreview>('/api/venus/import/sales', {
    method: 'POST',
    body: JSON.stringify({ mode: 'preview', dataB64, fileName }),
  });
export const applySalesImport = (token: string) =>
  authed<SalesImportApplyResult>('/api/venus/import/sales', {
    method: 'POST',
    body: JSON.stringify({ mode: 'apply', token }),
  });

export const applyCustomerImport = (token: string) =>
  authed<ImportApplyResult>('/api/venus/import/customers', {
    method: 'POST',
    body: JSON.stringify({ mode: 'apply', token }),
  });

// ── Display helpers ──────────────────────────────────────────────────────

// Dash-insensitive convention (see SKU display convention doc): store as-is, display bare
// where it helps scanning. Venus codes are shown as-is (they're not purely numeric SKUs),
// so no stripping here — kept for parity/documentation only.
export const creditLabel = (norm: VenusCustomer['creditTermsNorm']): string => {
  switch (norm) {
    case 'CASH': return 'เงินสด';
    case 'PREPAY': return 'โอนก่อนส่ง';
    case 'CREDIT': return 'เครดิต';
    case 'OTHER': return 'อื่นๆ';
    default: return '—';
  }
};

// Color per segment (VENUS_BRIEF.md §6 order: best -> worst). Used for the segment chip on
// the list row, the customer header, and the dashboard's segment distribution.
export const segmentColor = (s: Segment | null | undefined): string => {
  switch (s) {
    case 'ลูกค้าชั้นดี': return 'bg-emerald-100 text-emerald-700';
    case 'ลูกค้าประจำ': return 'bg-sky-100 text-sky-700';
    case 'มาใหม่': return 'bg-violet-100 text-violet-700';
    case 'เสี่ยงหาย': return 'bg-amber-100 text-amber-700';
    case 'หายไปแล้ว': return 'bg-slate-200 text-slate-500';
    default: return 'bg-slate-100 text-slate-400';
  }
};

export const formatBaht = (n: number | null | undefined): string =>
  n == null ? '—' : `฿${n.toLocaleString('th-TH', { maximumFractionDigits: 0 })}`;

export const formatDate = (d: string | Date | null | undefined): string => {
  if (!d) return '—';
  const date = typeof d === 'string' ? new Date(d) : d;
  if (Number.isNaN(date.getTime())) return '—';
  return date.toLocaleDateString('th-TH', { year: 'numeric', month: 'short', day: 'numeric' });
};

export const trendArrow = (dir: 'up' | 'down' | 'flat' | null | undefined): string =>
  dir === 'up' ? '▲' : dir === 'down' ? '▼' : '–';

export const trendColor = (dir: 'up' | 'down' | 'flat' | null | undefined): string =>
  dir === 'up' ? 'text-emerald-600' : dir === 'down' ? 'text-rose-600' : 'text-slate-400';
